// Generated by tools/gen_gles.py. Do not edit.
#pragma once

#include <bit>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <type_traits>

namespace zb {

using GLbitfield = std::uint32_t;
using GLboolean = std::uint8_t;
using GLchar = char;
using GLenum = std::uint32_t;
using GLfloat = float;
using GLint = std::int32_t;
using GLint64 = std::int64_t;
using GLintptr = std::intptr_t;
using GLsizei = std::int32_t;
using GLsizeiptr = std::ptrdiff_t;
using GLubyte = std::uint8_t;
using GLuint = std::uint32_t;
using GLuint64 = std::uint64_t;
// GLES 3.0 sync objects are driver pointers. They never reach the guest: HostGl hands
// out 32-bit handles and keeps the GLsync values host-side.
using GLsync = void*;

inline constexpr GLenum kGlInvalidValue = 0x0501;
inline constexpr GLenum kGlInvalidOperation = 0x0502;
inline constexpr GLenum kGlOutOfMemory = 0x0505;

template <typename T>
inline std::uint64_t gl_backend_word(T value) {
    if constexpr (std::is_pointer_v<T>) {
        return static_cast<std::uint64_t>(reinterpret_cast<std::uintptr_t>(value));
    } else if constexpr (std::is_floating_point_v<T>) {
        return std::bit_cast<std::uint32_t>(value);
    } else {
        return static_cast<std::uint64_t>(value);
    }
}

// The portable GLES seam. Android overrides the typed entry points; host tests use
// invoke() to record the same typed calls without linking a GLES implementation.
class GlBackend {
public:
    virtual ~GlBackend() = default;
    virtual void set_error(GLenum error) = 0;

    virtual void glActiveTexture(GLenum texture) {
        (void)invoke("glActiveTexture", {gl_backend_word(texture)});
    }
    virtual void glAttachShader(GLuint program, GLuint shader) {
        (void)invoke("glAttachShader", {gl_backend_word(program), gl_backend_word(shader)});
    }
    virtual void glBindAttribLocation(GLuint program, GLuint index, const GLchar *name) {
        (void)invoke("glBindAttribLocation", {gl_backend_word(program), gl_backend_word(index), gl_backend_word(name)});
    }
    virtual void glBindBuffer(GLenum target, GLuint buffer) {
        (void)invoke("glBindBuffer", {gl_backend_word(target), gl_backend_word(buffer)});
    }
    virtual void glBindFramebuffer(GLenum target, GLuint framebuffer) {
        (void)invoke("glBindFramebuffer", {gl_backend_word(target), gl_backend_word(framebuffer)});
    }
    virtual void glBindRenderbuffer(GLenum target, GLuint renderbuffer) {
        (void)invoke("glBindRenderbuffer", {gl_backend_word(target), gl_backend_word(renderbuffer)});
    }
    virtual void glBindTexture(GLenum target, GLuint texture) {
        (void)invoke("glBindTexture", {gl_backend_word(target), gl_backend_word(texture)});
    }
    virtual void glBlendColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
        (void)invoke("glBlendColor", {gl_backend_word(red), gl_backend_word(green), gl_backend_word(blue), gl_backend_word(alpha)});
    }
    virtual void glBlendEquation(GLenum mode) {
        (void)invoke("glBlendEquation", {gl_backend_word(mode)});
    }
    virtual void glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha) {
        (void)invoke("glBlendEquationSeparate", {gl_backend_word(modeRGB), gl_backend_word(modeAlpha)});
    }
    virtual void glBlendFunc(GLenum sfactor, GLenum dfactor) {
        (void)invoke("glBlendFunc", {gl_backend_word(sfactor), gl_backend_word(dfactor)});
    }
    virtual void glBlendFuncSeparate(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha) {
        (void)invoke("glBlendFuncSeparate", {gl_backend_word(sfactorRGB), gl_backend_word(dfactorRGB), gl_backend_word(sfactorAlpha), gl_backend_word(dfactorAlpha)});
    }
    virtual void glBufferData(GLenum target, GLsizeiptr size, const void *data, GLenum usage) {
        (void)invoke("glBufferData", {gl_backend_word(target), gl_backend_word(size), gl_backend_word(data), gl_backend_word(usage)});
    }
    virtual void glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void *data) {
        (void)invoke("glBufferSubData", {gl_backend_word(target), gl_backend_word(offset), gl_backend_word(size), gl_backend_word(data)});
    }
    virtual GLenum glCheckFramebufferStatus(GLenum target) {
        return static_cast<GLenum>(invoke("glCheckFramebufferStatus", {gl_backend_word(target)}));
    }
    virtual void glClear(GLbitfield mask) {
        (void)invoke("glClear", {gl_backend_word(mask)});
    }
    virtual void glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
        (void)invoke("glClearColor", {gl_backend_word(red), gl_backend_word(green), gl_backend_word(blue), gl_backend_word(alpha)});
    }
    virtual void glClearDepthf(GLfloat d) {
        (void)invoke("glClearDepthf", {gl_backend_word(d)});
    }
    virtual void glClearStencil(GLint s) {
        (void)invoke("glClearStencil", {gl_backend_word(s)});
    }
    virtual void glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) {
        (void)invoke("glColorMask", {gl_backend_word(red), gl_backend_word(green), gl_backend_word(blue), gl_backend_word(alpha)});
    }
    virtual void glCompileShader(GLuint shader) {
        (void)invoke("glCompileShader", {gl_backend_word(shader)});
    }
    virtual void glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data) {
        (void)invoke("glCompressedTexImage2D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height), gl_backend_word(border), gl_backend_word(imageSize), gl_backend_word(data)});
    }
    virtual void glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data) {
        (void)invoke("glCompressedTexSubImage2D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(xoffset), gl_backend_word(yoffset), gl_backend_word(width), gl_backend_word(height), gl_backend_word(format), gl_backend_word(imageSize), gl_backend_word(data)});
    }
    virtual void glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
        (void)invoke("glCopyTexImage2D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(internalformat), gl_backend_word(x), gl_backend_word(y), gl_backend_word(width), gl_backend_word(height), gl_backend_word(border)});
    }
    virtual void glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
        (void)invoke("glCopyTexSubImage2D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(xoffset), gl_backend_word(yoffset), gl_backend_word(x), gl_backend_word(y), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual GLuint glCreateProgram(void) {
        return static_cast<GLuint>(invoke("glCreateProgram", {}));
    }
    virtual GLuint glCreateShader(GLenum type) {
        return static_cast<GLuint>(invoke("glCreateShader", {gl_backend_word(type)}));
    }
    virtual void glCullFace(GLenum mode) {
        (void)invoke("glCullFace", {gl_backend_word(mode)});
    }
    virtual void glDeleteBuffers(GLsizei n, const GLuint *buffers) {
        (void)invoke("glDeleteBuffers", {gl_backend_word(n), gl_backend_word(buffers)});
    }
    virtual void glDeleteFramebuffers(GLsizei n, const GLuint *framebuffers) {
        (void)invoke("glDeleteFramebuffers", {gl_backend_word(n), gl_backend_word(framebuffers)});
    }
    virtual void glDeleteProgram(GLuint program) {
        (void)invoke("glDeleteProgram", {gl_backend_word(program)});
    }
    virtual void glDeleteRenderbuffers(GLsizei n, const GLuint *renderbuffers) {
        (void)invoke("glDeleteRenderbuffers", {gl_backend_word(n), gl_backend_word(renderbuffers)});
    }
    virtual void glDeleteShader(GLuint shader) {
        (void)invoke("glDeleteShader", {gl_backend_word(shader)});
    }
    virtual void glDeleteTextures(GLsizei n, const GLuint *textures) {
        (void)invoke("glDeleteTextures", {gl_backend_word(n), gl_backend_word(textures)});
    }
    virtual void glDepthFunc(GLenum func) {
        (void)invoke("glDepthFunc", {gl_backend_word(func)});
    }
    virtual void glDepthMask(GLboolean flag) {
        (void)invoke("glDepthMask", {gl_backend_word(flag)});
    }
    virtual void glDepthRangef(GLfloat n, GLfloat f) {
        (void)invoke("glDepthRangef", {gl_backend_word(n), gl_backend_word(f)});
    }
    virtual void glDetachShader(GLuint program, GLuint shader) {
        (void)invoke("glDetachShader", {gl_backend_word(program), gl_backend_word(shader)});
    }
    virtual void glDisable(GLenum cap) {
        (void)invoke("glDisable", {gl_backend_word(cap)});
    }
    virtual void glDisableVertexAttribArray(GLuint index) {
        (void)invoke("glDisableVertexAttribArray", {gl_backend_word(index)});
    }
    virtual void glDrawArrays(GLenum mode, GLint first, GLsizei count) {
        (void)invoke("glDrawArrays", {gl_backend_word(mode), gl_backend_word(first), gl_backend_word(count)});
    }
    virtual void glDrawElements(GLenum mode, GLsizei count, GLenum type, const void *indices) {
        (void)invoke("glDrawElements", {gl_backend_word(mode), gl_backend_word(count), gl_backend_word(type), gl_backend_word(indices)});
    }
    virtual void glEnable(GLenum cap) {
        (void)invoke("glEnable", {gl_backend_word(cap)});
    }
    virtual void glEnableVertexAttribArray(GLuint index) {
        (void)invoke("glEnableVertexAttribArray", {gl_backend_word(index)});
    }
    virtual void glFinish(void) {
        (void)invoke("glFinish", {});
    }
    virtual void glFlush(void) {
        (void)invoke("glFlush", {});
    }
    virtual void glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
        (void)invoke("glFramebufferRenderbuffer", {gl_backend_word(target), gl_backend_word(attachment), gl_backend_word(renderbuffertarget), gl_backend_word(renderbuffer)});
    }
    virtual void glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
        (void)invoke("glFramebufferTexture2D", {gl_backend_word(target), gl_backend_word(attachment), gl_backend_word(textarget), gl_backend_word(texture), gl_backend_word(level)});
    }
    virtual void glFrontFace(GLenum mode) {
        (void)invoke("glFrontFace", {gl_backend_word(mode)});
    }
    virtual void glGenBuffers(GLsizei n, GLuint *buffers) {
        (void)invoke("glGenBuffers", {gl_backend_word(n), gl_backend_word(buffers)});
    }
    virtual void glGenFramebuffers(GLsizei n, GLuint *framebuffers) {
        (void)invoke("glGenFramebuffers", {gl_backend_word(n), gl_backend_word(framebuffers)});
    }
    virtual void glGenRenderbuffers(GLsizei n, GLuint *renderbuffers) {
        (void)invoke("glGenRenderbuffers", {gl_backend_word(n), gl_backend_word(renderbuffers)});
    }
    virtual void glGenTextures(GLsizei n, GLuint *textures) {
        (void)invoke("glGenTextures", {gl_backend_word(n), gl_backend_word(textures)});
    }
    virtual void glGenerateMipmap(GLenum target) {
        (void)invoke("glGenerateMipmap", {gl_backend_word(target)});
    }
    virtual void glGetActiveAttrib(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name) {
        (void)invoke("glGetActiveAttrib", {gl_backend_word(program), gl_backend_word(index), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(size), gl_backend_word(type), gl_backend_word(name)});
    }
    virtual void glGetActiveUniform(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name) {
        (void)invoke("glGetActiveUniform", {gl_backend_word(program), gl_backend_word(index), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(size), gl_backend_word(type), gl_backend_word(name)});
    }
    virtual void glGetAttachedShaders(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders) {
        (void)invoke("glGetAttachedShaders", {gl_backend_word(program), gl_backend_word(maxCount), gl_backend_word(count), gl_backend_word(shaders)});
    }
    virtual GLint glGetAttribLocation(GLuint program, const GLchar *name) {
        return static_cast<GLint>(invoke("glGetAttribLocation", {gl_backend_word(program), gl_backend_word(name)}));
    }
    virtual void glGetBooleanv(GLenum pname, GLboolean *data) {
        (void)invoke("glGetBooleanv", {gl_backend_word(pname), gl_backend_word(data)});
    }
    virtual void glGetBufferParameteriv(GLenum target, GLenum pname, GLint *params) {
        (void)invoke("glGetBufferParameteriv", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual GLenum glGetError(void) {
        return static_cast<GLenum>(invoke("glGetError", {}));
    }
    virtual void glGetFloatv(GLenum pname, GLfloat *data) {
        (void)invoke("glGetFloatv", {gl_backend_word(pname), gl_backend_word(data)});
    }
    virtual void glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint *params) {
        (void)invoke("glGetFramebufferAttachmentParameteriv", {gl_backend_word(target), gl_backend_word(attachment), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetIntegerv(GLenum pname, GLint *data) {
        (void)invoke("glGetIntegerv", {gl_backend_word(pname), gl_backend_word(data)});
    }
    virtual void glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog) {
        (void)invoke("glGetProgramInfoLog", {gl_backend_word(program), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(infoLog)});
    }
    virtual void glGetProgramiv(GLuint program, GLenum pname, GLint *params) {
        (void)invoke("glGetProgramiv", {gl_backend_word(program), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint *params) {
        (void)invoke("glGetRenderbufferParameteriv", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog) {
        (void)invoke("glGetShaderInfoLog", {gl_backend_word(shader), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(infoLog)});
    }
    virtual void glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision) {
        (void)invoke("glGetShaderPrecisionFormat", {gl_backend_word(shadertype), gl_backend_word(precisiontype), gl_backend_word(range), gl_backend_word(precision)});
    }
    virtual void glGetShaderSource(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source) {
        (void)invoke("glGetShaderSource", {gl_backend_word(shader), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(source)});
    }
    virtual void glGetShaderiv(GLuint shader, GLenum pname, GLint *params) {
        (void)invoke("glGetShaderiv", {gl_backend_word(shader), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual const GLubyte * glGetString(GLenum name) {
        return reinterpret_cast<const GLubyte *>(static_cast<std::uintptr_t>(invoke("glGetString", {gl_backend_word(name)})));
    }
    virtual void glGetTexParameterfv(GLenum target, GLenum pname, GLfloat *params) {
        (void)invoke("glGetTexParameterfv", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetTexParameteriv(GLenum target, GLenum pname, GLint *params) {
        (void)invoke("glGetTexParameteriv", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual GLint glGetUniformLocation(GLuint program, const GLchar *name) {
        return static_cast<GLint>(invoke("glGetUniformLocation", {gl_backend_word(program), gl_backend_word(name)}));
    }
    virtual void glGetUniformfv(GLuint program, GLint location, GLfloat *params) {
        (void)invoke("glGetUniformfv", {gl_backend_word(program), gl_backend_word(location), gl_backend_word(params)});
    }
    virtual void glGetUniformiv(GLuint program, GLint location, GLint *params) {
        (void)invoke("glGetUniformiv", {gl_backend_word(program), gl_backend_word(location), gl_backend_word(params)});
    }
    virtual void glGetVertexAttribPointerv(GLuint index, GLenum pname, void **pointer) {
        (void)invoke("glGetVertexAttribPointerv", {gl_backend_word(index), gl_backend_word(pname), gl_backend_word(pointer)});
    }
    virtual void glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat *params) {
        (void)invoke("glGetVertexAttribfv", {gl_backend_word(index), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetVertexAttribiv(GLuint index, GLenum pname, GLint *params) {
        (void)invoke("glGetVertexAttribiv", {gl_backend_word(index), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glHint(GLenum target, GLenum mode) {
        (void)invoke("glHint", {gl_backend_word(target), gl_backend_word(mode)});
    }
    virtual GLboolean glIsBuffer(GLuint buffer) {
        return static_cast<GLboolean>(invoke("glIsBuffer", {gl_backend_word(buffer)}));
    }
    virtual GLboolean glIsEnabled(GLenum cap) {
        return static_cast<GLboolean>(invoke("glIsEnabled", {gl_backend_word(cap)}));
    }
    virtual GLboolean glIsFramebuffer(GLuint framebuffer) {
        return static_cast<GLboolean>(invoke("glIsFramebuffer", {gl_backend_word(framebuffer)}));
    }
    virtual GLboolean glIsProgram(GLuint program) {
        return static_cast<GLboolean>(invoke("glIsProgram", {gl_backend_word(program)}));
    }
    virtual GLboolean glIsRenderbuffer(GLuint renderbuffer) {
        return static_cast<GLboolean>(invoke("glIsRenderbuffer", {gl_backend_word(renderbuffer)}));
    }
    virtual GLboolean glIsShader(GLuint shader) {
        return static_cast<GLboolean>(invoke("glIsShader", {gl_backend_word(shader)}));
    }
    virtual GLboolean glIsTexture(GLuint texture) {
        return static_cast<GLboolean>(invoke("glIsTexture", {gl_backend_word(texture)}));
    }
    virtual void glLineWidth(GLfloat width) {
        (void)invoke("glLineWidth", {gl_backend_word(width)});
    }
    virtual void glLinkProgram(GLuint program) {
        (void)invoke("glLinkProgram", {gl_backend_word(program)});
    }
    virtual void glPixelStorei(GLenum pname, GLint param) {
        (void)invoke("glPixelStorei", {gl_backend_word(pname), gl_backend_word(param)});
    }
    virtual void glPolygonOffset(GLfloat factor, GLfloat units) {
        (void)invoke("glPolygonOffset", {gl_backend_word(factor), gl_backend_word(units)});
    }
    virtual void glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels) {
        (void)invoke("glReadPixels", {gl_backend_word(x), gl_backend_word(y), gl_backend_word(width), gl_backend_word(height), gl_backend_word(format), gl_backend_word(type), gl_backend_word(pixels)});
    }
    virtual void glReleaseShaderCompiler(void) {
        (void)invoke("glReleaseShaderCompiler", {});
    }
    virtual void glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) {
        (void)invoke("glRenderbufferStorage", {gl_backend_word(target), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual void glSampleCoverage(GLfloat value, GLboolean invert) {
        (void)invoke("glSampleCoverage", {gl_backend_word(value), gl_backend_word(invert)});
    }
    virtual void glScissor(GLint x, GLint y, GLsizei width, GLsizei height) {
        (void)invoke("glScissor", {gl_backend_word(x), gl_backend_word(y), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual void glShaderBinary(GLsizei count, const GLuint *shaders, GLenum binaryFormat, const void *binary, GLsizei length) {
        (void)invoke("glShaderBinary", {gl_backend_word(count), gl_backend_word(shaders), gl_backend_word(binaryFormat), gl_backend_word(binary), gl_backend_word(length)});
    }
    virtual void glShaderSource(GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length) {
        (void)invoke("glShaderSource", {gl_backend_word(shader), gl_backend_word(count), gl_backend_word(string), gl_backend_word(length)});
    }
    virtual void glStencilFunc(GLenum func, GLint ref, GLuint mask) {
        (void)invoke("glStencilFunc", {gl_backend_word(func), gl_backend_word(ref), gl_backend_word(mask)});
    }
    virtual void glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask) {
        (void)invoke("glStencilFuncSeparate", {gl_backend_word(face), gl_backend_word(func), gl_backend_word(ref), gl_backend_word(mask)});
    }
    virtual void glStencilMask(GLuint mask) {
        (void)invoke("glStencilMask", {gl_backend_word(mask)});
    }
    virtual void glStencilMaskSeparate(GLenum face, GLuint mask) {
        (void)invoke("glStencilMaskSeparate", {gl_backend_word(face), gl_backend_word(mask)});
    }
    virtual void glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) {
        (void)invoke("glStencilOp", {gl_backend_word(fail), gl_backend_word(zfail), gl_backend_word(zpass)});
    }
    virtual void glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass) {
        (void)invoke("glStencilOpSeparate", {gl_backend_word(face), gl_backend_word(sfail), gl_backend_word(dpfail), gl_backend_word(dppass)});
    }
    virtual void glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels) {
        (void)invoke("glTexImage2D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height), gl_backend_word(border), gl_backend_word(format), gl_backend_word(type), gl_backend_word(pixels)});
    }
    virtual void glTexParameterf(GLenum target, GLenum pname, GLfloat param) {
        (void)invoke("glTexParameterf", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(param)});
    }
    virtual void glTexParameterfv(GLenum target, GLenum pname, const GLfloat *params) {
        (void)invoke("glTexParameterfv", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glTexParameteri(GLenum target, GLenum pname, GLint param) {
        (void)invoke("glTexParameteri", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(param)});
    }
    virtual void glTexParameteriv(GLenum target, GLenum pname, const GLint *params) {
        (void)invoke("glTexParameteriv", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels) {
        (void)invoke("glTexSubImage2D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(xoffset), gl_backend_word(yoffset), gl_backend_word(width), gl_backend_word(height), gl_backend_word(format), gl_backend_word(type), gl_backend_word(pixels)});
    }
    virtual void glUniform1f(GLint location, GLfloat v0) {
        (void)invoke("glUniform1f", {gl_backend_word(location), gl_backend_word(v0)});
    }
    virtual void glUniform1fv(GLint location, GLsizei count, const GLfloat *value) {
        (void)invoke("glUniform1fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform1i(GLint location, GLint v0) {
        (void)invoke("glUniform1i", {gl_backend_word(location), gl_backend_word(v0)});
    }
    virtual void glUniform1iv(GLint location, GLsizei count, const GLint *value) {
        (void)invoke("glUniform1iv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform2f(GLint location, GLfloat v0, GLfloat v1) {
        (void)invoke("glUniform2f", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1)});
    }
    virtual void glUniform2fv(GLint location, GLsizei count, const GLfloat *value) {
        (void)invoke("glUniform2fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform2i(GLint location, GLint v0, GLint v1) {
        (void)invoke("glUniform2i", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1)});
    }
    virtual void glUniform2iv(GLint location, GLsizei count, const GLint *value) {
        (void)invoke("glUniform2iv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) {
        (void)invoke("glUniform3f", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1), gl_backend_word(v2)});
    }
    virtual void glUniform3fv(GLint location, GLsizei count, const GLfloat *value) {
        (void)invoke("glUniform3fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform3i(GLint location, GLint v0, GLint v1, GLint v2) {
        (void)invoke("glUniform3i", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1), gl_backend_word(v2)});
    }
    virtual void glUniform3iv(GLint location, GLsizei count, const GLint *value) {
        (void)invoke("glUniform3iv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) {
        (void)invoke("glUniform4f", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1), gl_backend_word(v2), gl_backend_word(v3)});
    }
    virtual void glUniform4fv(GLint location, GLsizei count, const GLfloat *value) {
        (void)invoke("glUniform4fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) {
        (void)invoke("glUniform4i", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1), gl_backend_word(v2), gl_backend_word(v3)});
    }
    virtual void glUniform4iv(GLint location, GLsizei count, const GLint *value) {
        (void)invoke("glUniform4iv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix2fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual void glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix3fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual void glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix4fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual void glUseProgram(GLuint program) {
        (void)invoke("glUseProgram", {gl_backend_word(program)});
    }
    virtual void glValidateProgram(GLuint program) {
        (void)invoke("glValidateProgram", {gl_backend_word(program)});
    }
    virtual void glVertexAttrib1f(GLuint index, GLfloat x) {
        (void)invoke("glVertexAttrib1f", {gl_backend_word(index), gl_backend_word(x)});
    }
    virtual void glVertexAttrib1fv(GLuint index, const GLfloat *v) {
        (void)invoke("glVertexAttrib1fv", {gl_backend_word(index), gl_backend_word(v)});
    }
    virtual void glVertexAttrib2f(GLuint index, GLfloat x, GLfloat y) {
        (void)invoke("glVertexAttrib2f", {gl_backend_word(index), gl_backend_word(x), gl_backend_word(y)});
    }
    virtual void glVertexAttrib2fv(GLuint index, const GLfloat *v) {
        (void)invoke("glVertexAttrib2fv", {gl_backend_word(index), gl_backend_word(v)});
    }
    virtual void glVertexAttrib3f(GLuint index, GLfloat x, GLfloat y, GLfloat z) {
        (void)invoke("glVertexAttrib3f", {gl_backend_word(index), gl_backend_word(x), gl_backend_word(y), gl_backend_word(z)});
    }
    virtual void glVertexAttrib3fv(GLuint index, const GLfloat *v) {
        (void)invoke("glVertexAttrib3fv", {gl_backend_word(index), gl_backend_word(v)});
    }
    virtual void glVertexAttrib4f(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
        (void)invoke("glVertexAttrib4f", {gl_backend_word(index), gl_backend_word(x), gl_backend_word(y), gl_backend_word(z), gl_backend_word(w)});
    }
    virtual void glVertexAttrib4fv(GLuint index, const GLfloat *v) {
        (void)invoke("glVertexAttrib4fv", {gl_backend_word(index), gl_backend_word(v)});
    }
    virtual void glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer) {
        (void)invoke("glVertexAttribPointer", {gl_backend_word(index), gl_backend_word(size), gl_backend_word(type), gl_backend_word(normalized), gl_backend_word(stride), gl_backend_word(pointer)});
    }
    virtual void glViewport(GLint x, GLint y, GLsizei width, GLsizei height) {
        (void)invoke("glViewport", {gl_backend_word(x), gl_backend_word(y), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual void glBeginQuery(GLenum target, GLuint id) {
        (void)invoke("glBeginQuery", {gl_backend_word(target), gl_backend_word(id)});
    }
    virtual void glBeginTransformFeedback(GLenum primitiveMode) {
        (void)invoke("glBeginTransformFeedback", {gl_backend_word(primitiveMode)});
    }
    virtual void glBindBufferBase(GLenum target, GLuint index, GLuint buffer) {
        (void)invoke("glBindBufferBase", {gl_backend_word(target), gl_backend_word(index), gl_backend_word(buffer)});
    }
    virtual void glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size) {
        (void)invoke("glBindBufferRange", {gl_backend_word(target), gl_backend_word(index), gl_backend_word(buffer), gl_backend_word(offset), gl_backend_word(size)});
    }
    virtual void glBindSampler(GLuint unit, GLuint sampler) {
        (void)invoke("glBindSampler", {gl_backend_word(unit), gl_backend_word(sampler)});
    }
    virtual void glBindTransformFeedback(GLenum target, GLuint id) {
        (void)invoke("glBindTransformFeedback", {gl_backend_word(target), gl_backend_word(id)});
    }
    virtual void glBindVertexArray(GLuint array) {
        (void)invoke("glBindVertexArray", {gl_backend_word(array)});
    }
    virtual void glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter) {
        (void)invoke("glBlitFramebuffer", {gl_backend_word(srcX0), gl_backend_word(srcY0), gl_backend_word(srcX1), gl_backend_word(srcY1), gl_backend_word(dstX0), gl_backend_word(dstY0), gl_backend_word(dstX1), gl_backend_word(dstY1), gl_backend_word(mask), gl_backend_word(filter)});
    }
    virtual void glClearBufferfi(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil) {
        (void)invoke("glClearBufferfi", {gl_backend_word(buffer), gl_backend_word(drawbuffer), gl_backend_word(depth), gl_backend_word(stencil)});
    }
    virtual void glClearBufferfv(GLenum buffer, GLint drawbuffer, const GLfloat *value) {
        (void)invoke("glClearBufferfv", {gl_backend_word(buffer), gl_backend_word(drawbuffer), gl_backend_word(value)});
    }
    virtual void glClearBufferiv(GLenum buffer, GLint drawbuffer, const GLint *value) {
        (void)invoke("glClearBufferiv", {gl_backend_word(buffer), gl_backend_word(drawbuffer), gl_backend_word(value)});
    }
    virtual void glClearBufferuiv(GLenum buffer, GLint drawbuffer, const GLuint *value) {
        (void)invoke("glClearBufferuiv", {gl_backend_word(buffer), gl_backend_word(drawbuffer), gl_backend_word(value)});
    }
    virtual GLenum glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
        return static_cast<GLenum>(invoke("glClientWaitSync", {gl_backend_word(sync), gl_backend_word(flags), gl_backend_word(timeout)}));
    }
    virtual void glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data) {
        (void)invoke("glCompressedTexImage3D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height), gl_backend_word(depth), gl_backend_word(border), gl_backend_word(imageSize), gl_backend_word(data)});
    }
    virtual void glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data) {
        (void)invoke("glCompressedTexSubImage3D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(xoffset), gl_backend_word(yoffset), gl_backend_word(zoffset), gl_backend_word(width), gl_backend_word(height), gl_backend_word(depth), gl_backend_word(format), gl_backend_word(imageSize), gl_backend_word(data)});
    }
    virtual void glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size) {
        (void)invoke("glCopyBufferSubData", {gl_backend_word(readTarget), gl_backend_word(writeTarget), gl_backend_word(readOffset), gl_backend_word(writeOffset), gl_backend_word(size)});
    }
    virtual void glCopyTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
        (void)invoke("glCopyTexSubImage3D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(xoffset), gl_backend_word(yoffset), gl_backend_word(zoffset), gl_backend_word(x), gl_backend_word(y), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual void glDeleteQueries(GLsizei n, const GLuint *ids) {
        (void)invoke("glDeleteQueries", {gl_backend_word(n), gl_backend_word(ids)});
    }
    virtual void glDeleteSamplers(GLsizei count, const GLuint *samplers) {
        (void)invoke("glDeleteSamplers", {gl_backend_word(count), gl_backend_word(samplers)});
    }
    virtual void glDeleteSync(GLsync sync) {
        (void)invoke("glDeleteSync", {gl_backend_word(sync)});
    }
    virtual void glDeleteTransformFeedbacks(GLsizei n, const GLuint *ids) {
        (void)invoke("glDeleteTransformFeedbacks", {gl_backend_word(n), gl_backend_word(ids)});
    }
    virtual void glDeleteVertexArrays(GLsizei n, const GLuint *arrays) {
        (void)invoke("glDeleteVertexArrays", {gl_backend_word(n), gl_backend_word(arrays)});
    }
    virtual void glDrawArraysInstanced(GLenum mode, GLint first, GLsizei count, GLsizei instancecount) {
        (void)invoke("glDrawArraysInstanced", {gl_backend_word(mode), gl_backend_word(first), gl_backend_word(count), gl_backend_word(instancecount)});
    }
    virtual void glDrawBuffers(GLsizei n, const GLenum *bufs) {
        (void)invoke("glDrawBuffers", {gl_backend_word(n), gl_backend_word(bufs)});
    }
    virtual void glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount) {
        (void)invoke("glDrawElementsInstanced", {gl_backend_word(mode), gl_backend_word(count), gl_backend_word(type), gl_backend_word(indices), gl_backend_word(instancecount)});
    }
    virtual void glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices) {
        (void)invoke("glDrawRangeElements", {gl_backend_word(mode), gl_backend_word(start), gl_backend_word(end), gl_backend_word(count), gl_backend_word(type), gl_backend_word(indices)});
    }
    virtual void glEndQuery(GLenum target) {
        (void)invoke("glEndQuery", {gl_backend_word(target)});
    }
    virtual void glEndTransformFeedback(void) {
        (void)invoke("glEndTransformFeedback", {});
    }
    virtual GLsync glFenceSync(GLenum condition, GLbitfield flags) {
        return reinterpret_cast<GLsync>(static_cast<std::uintptr_t>(invoke("glFenceSync", {gl_backend_word(condition), gl_backend_word(flags)})));
    }
    virtual void glFlushMappedBufferRange(GLenum target, GLintptr offset, GLsizeiptr length) {
        (void)invoke("glFlushMappedBufferRange", {gl_backend_word(target), gl_backend_word(offset), gl_backend_word(length)});
    }
    virtual void glFramebufferTextureLayer(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer) {
        (void)invoke("glFramebufferTextureLayer", {gl_backend_word(target), gl_backend_word(attachment), gl_backend_word(texture), gl_backend_word(level), gl_backend_word(layer)});
    }
    virtual void glGenQueries(GLsizei n, GLuint *ids) {
        (void)invoke("glGenQueries", {gl_backend_word(n), gl_backend_word(ids)});
    }
    virtual void glGenSamplers(GLsizei count, GLuint *samplers) {
        (void)invoke("glGenSamplers", {gl_backend_word(count), gl_backend_word(samplers)});
    }
    virtual void glGenTransformFeedbacks(GLsizei n, GLuint *ids) {
        (void)invoke("glGenTransformFeedbacks", {gl_backend_word(n), gl_backend_word(ids)});
    }
    virtual void glGenVertexArrays(GLsizei n, GLuint *arrays) {
        (void)invoke("glGenVertexArrays", {gl_backend_word(n), gl_backend_word(arrays)});
    }
    virtual void glGetActiveUniformBlockName(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName) {
        (void)invoke("glGetActiveUniformBlockName", {gl_backend_word(program), gl_backend_word(uniformBlockIndex), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(uniformBlockName)});
    }
    virtual void glGetActiveUniformBlockiv(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params) {
        (void)invoke("glGetActiveUniformBlockiv", {gl_backend_word(program), gl_backend_word(uniformBlockIndex), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetActiveUniformsiv(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params) {
        (void)invoke("glGetActiveUniformsiv", {gl_backend_word(program), gl_backend_word(uniformCount), gl_backend_word(uniformIndices), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetBufferParameteri64v(GLenum target, GLenum pname, GLint64 *params) {
        (void)invoke("glGetBufferParameteri64v", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetBufferPointerv(GLenum target, GLenum pname, void **params) {
        (void)invoke("glGetBufferPointerv", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual GLint glGetFragDataLocation(GLuint program, const GLchar *name) {
        return static_cast<GLint>(invoke("glGetFragDataLocation", {gl_backend_word(program), gl_backend_word(name)}));
    }
    virtual void glGetInteger64i_v(GLenum target, GLuint index, GLint64 *data) {
        (void)invoke("glGetInteger64i_v", {gl_backend_word(target), gl_backend_word(index), gl_backend_word(data)});
    }
    virtual void glGetInteger64v(GLenum pname, GLint64 *data) {
        (void)invoke("glGetInteger64v", {gl_backend_word(pname), gl_backend_word(data)});
    }
    virtual void glGetIntegeri_v(GLenum target, GLuint index, GLint *data) {
        (void)invoke("glGetIntegeri_v", {gl_backend_word(target), gl_backend_word(index), gl_backend_word(data)});
    }
    virtual void glGetInternalformativ(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint *params) {
        (void)invoke("glGetInternalformativ", {gl_backend_word(target), gl_backend_word(internalformat), gl_backend_word(pname), gl_backend_word(count), gl_backend_word(params)});
    }
    virtual void glGetProgramBinary(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary) {
        (void)invoke("glGetProgramBinary", {gl_backend_word(program), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(binaryFormat), gl_backend_word(binary)});
    }
    virtual void glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint *params) {
        (void)invoke("glGetQueryObjectuiv", {gl_backend_word(id), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetQueryiv(GLenum target, GLenum pname, GLint *params) {
        (void)invoke("glGetQueryiv", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetSamplerParameterfv(GLuint sampler, GLenum pname, GLfloat *params) {
        (void)invoke("glGetSamplerParameterfv", {gl_backend_word(sampler), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetSamplerParameteriv(GLuint sampler, GLenum pname, GLint *params) {
        (void)invoke("glGetSamplerParameteriv", {gl_backend_word(sampler), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual const GLubyte * glGetStringi(GLenum name, GLuint index) {
        return reinterpret_cast<const GLubyte *>(static_cast<std::uintptr_t>(invoke("glGetStringi", {gl_backend_word(name), gl_backend_word(index)})));
    }
    virtual void glGetSynciv(GLsync sync, GLenum pname, GLsizei count, GLsizei *length, GLint *values) {
        (void)invoke("glGetSynciv", {gl_backend_word(sync), gl_backend_word(pname), gl_backend_word(count), gl_backend_word(length), gl_backend_word(values)});
    }
    virtual void glGetTransformFeedbackVarying(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name) {
        (void)invoke("glGetTransformFeedbackVarying", {gl_backend_word(program), gl_backend_word(index), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(size), gl_backend_word(type), gl_backend_word(name)});
    }
    virtual GLuint glGetUniformBlockIndex(GLuint program, const GLchar *uniformBlockName) {
        return static_cast<GLuint>(invoke("glGetUniformBlockIndex", {gl_backend_word(program), gl_backend_word(uniformBlockName)}));
    }
    virtual void glGetUniformIndices(GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices) {
        (void)invoke("glGetUniformIndices", {gl_backend_word(program), gl_backend_word(uniformCount), gl_backend_word(uniformNames), gl_backend_word(uniformIndices)});
    }
    virtual void glGetUniformuiv(GLuint program, GLint location, GLuint *params) {
        (void)invoke("glGetUniformuiv", {gl_backend_word(program), gl_backend_word(location), gl_backend_word(params)});
    }
    virtual void glGetVertexAttribIiv(GLuint index, GLenum pname, GLint *params) {
        (void)invoke("glGetVertexAttribIiv", {gl_backend_word(index), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glGetVertexAttribIuiv(GLuint index, GLenum pname, GLuint *params) {
        (void)invoke("glGetVertexAttribIuiv", {gl_backend_word(index), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glInvalidateFramebuffer(GLenum target, GLsizei numAttachments, const GLenum *attachments) {
        (void)invoke("glInvalidateFramebuffer", {gl_backend_word(target), gl_backend_word(numAttachments), gl_backend_word(attachments)});
    }
    virtual void glInvalidateSubFramebuffer(GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height) {
        (void)invoke("glInvalidateSubFramebuffer", {gl_backend_word(target), gl_backend_word(numAttachments), gl_backend_word(attachments), gl_backend_word(x), gl_backend_word(y), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual GLboolean glIsQuery(GLuint id) {
        return static_cast<GLboolean>(invoke("glIsQuery", {gl_backend_word(id)}));
    }
    virtual GLboolean glIsSampler(GLuint sampler) {
        return static_cast<GLboolean>(invoke("glIsSampler", {gl_backend_word(sampler)}));
    }
    virtual GLboolean glIsSync(GLsync sync) {
        return static_cast<GLboolean>(invoke("glIsSync", {gl_backend_word(sync)}));
    }
    virtual GLboolean glIsTransformFeedback(GLuint id) {
        return static_cast<GLboolean>(invoke("glIsTransformFeedback", {gl_backend_word(id)}));
    }
    virtual GLboolean glIsVertexArray(GLuint array) {
        return static_cast<GLboolean>(invoke("glIsVertexArray", {gl_backend_word(array)}));
    }
    virtual void * glMapBufferRange(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access) {
        return reinterpret_cast<void *>(static_cast<std::uintptr_t>(invoke("glMapBufferRange", {gl_backend_word(target), gl_backend_word(offset), gl_backend_word(length), gl_backend_word(access)})));
    }
    virtual void glPauseTransformFeedback(void) {
        (void)invoke("glPauseTransformFeedback", {});
    }
    virtual void glProgramBinary(GLuint program, GLenum binaryFormat, const void *binary, GLsizei length) {
        (void)invoke("glProgramBinary", {gl_backend_word(program), gl_backend_word(binaryFormat), gl_backend_word(binary), gl_backend_word(length)});
    }
    virtual void glProgramParameteri(GLuint program, GLenum pname, GLint value) {
        (void)invoke("glProgramParameteri", {gl_backend_word(program), gl_backend_word(pname), gl_backend_word(value)});
    }
    virtual void glReadBuffer(GLenum src) {
        (void)invoke("glReadBuffer", {gl_backend_word(src)});
    }
    virtual void glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height) {
        (void)invoke("glRenderbufferStorageMultisample", {gl_backend_word(target), gl_backend_word(samples), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual void glResumeTransformFeedback(void) {
        (void)invoke("glResumeTransformFeedback", {});
    }
    virtual void glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param) {
        (void)invoke("glSamplerParameterf", {gl_backend_word(sampler), gl_backend_word(pname), gl_backend_word(param)});
    }
    virtual void glSamplerParameterfv(GLuint sampler, GLenum pname, const GLfloat *param) {
        (void)invoke("glSamplerParameterfv", {gl_backend_word(sampler), gl_backend_word(pname), gl_backend_word(param)});
    }
    virtual void glSamplerParameteri(GLuint sampler, GLenum pname, GLint param) {
        (void)invoke("glSamplerParameteri", {gl_backend_word(sampler), gl_backend_word(pname), gl_backend_word(param)});
    }
    virtual void glSamplerParameteriv(GLuint sampler, GLenum pname, const GLint *param) {
        (void)invoke("glSamplerParameteriv", {gl_backend_word(sampler), gl_backend_word(pname), gl_backend_word(param)});
    }
    virtual void glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels) {
        (void)invoke("glTexImage3D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height), gl_backend_word(depth), gl_backend_word(border), gl_backend_word(format), gl_backend_word(type), gl_backend_word(pixels)});
    }
    virtual void glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height) {
        (void)invoke("glTexStorage2D", {gl_backend_word(target), gl_backend_word(levels), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual void glTexStorage3D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth) {
        (void)invoke("glTexStorage3D", {gl_backend_word(target), gl_backend_word(levels), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height), gl_backend_word(depth)});
    }
    virtual void glTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels) {
        (void)invoke("glTexSubImage3D", {gl_backend_word(target), gl_backend_word(level), gl_backend_word(xoffset), gl_backend_word(yoffset), gl_backend_word(zoffset), gl_backend_word(width), gl_backend_word(height), gl_backend_word(depth), gl_backend_word(format), gl_backend_word(type), gl_backend_word(pixels)});
    }
    virtual void glTransformFeedbackVaryings(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode) {
        (void)invoke("glTransformFeedbackVaryings", {gl_backend_word(program), gl_backend_word(count), gl_backend_word(varyings), gl_backend_word(bufferMode)});
    }
    virtual void glUniform1ui(GLint location, GLuint v0) {
        (void)invoke("glUniform1ui", {gl_backend_word(location), gl_backend_word(v0)});
    }
    virtual void glUniform1uiv(GLint location, GLsizei count, const GLuint *value) {
        (void)invoke("glUniform1uiv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform2ui(GLint location, GLuint v0, GLuint v1) {
        (void)invoke("glUniform2ui", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1)});
    }
    virtual void glUniform2uiv(GLint location, GLsizei count, const GLuint *value) {
        (void)invoke("glUniform2uiv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform3ui(GLint location, GLuint v0, GLuint v1, GLuint v2) {
        (void)invoke("glUniform3ui", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1), gl_backend_word(v2)});
    }
    virtual void glUniform3uiv(GLint location, GLsizei count, const GLuint *value) {
        (void)invoke("glUniform3uiv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniform4ui(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3) {
        (void)invoke("glUniform4ui", {gl_backend_word(location), gl_backend_word(v0), gl_backend_word(v1), gl_backend_word(v2), gl_backend_word(v3)});
    }
    virtual void glUniform4uiv(GLint location, GLsizei count, const GLuint *value) {
        (void)invoke("glUniform4uiv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(value)});
    }
    virtual void glUniformBlockBinding(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding) {
        (void)invoke("glUniformBlockBinding", {gl_backend_word(program), gl_backend_word(uniformBlockIndex), gl_backend_word(uniformBlockBinding)});
    }
    virtual void glUniformMatrix2x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix2x3fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual void glUniformMatrix2x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix2x4fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual void glUniformMatrix3x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix3x2fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual void glUniformMatrix3x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix3x4fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual void glUniformMatrix4x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix4x2fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual void glUniformMatrix4x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
        (void)invoke("glUniformMatrix4x3fv", {gl_backend_word(location), gl_backend_word(count), gl_backend_word(transpose), gl_backend_word(value)});
    }
    virtual GLboolean glUnmapBuffer(GLenum target) {
        return static_cast<GLboolean>(invoke("glUnmapBuffer", {gl_backend_word(target)}));
    }
    virtual void glVertexAttribDivisor(GLuint index, GLuint divisor) {
        (void)invoke("glVertexAttribDivisor", {gl_backend_word(index), gl_backend_word(divisor)});
    }
    virtual void glVertexAttribI4i(GLuint index, GLint x, GLint y, GLint z, GLint w) {
        (void)invoke("glVertexAttribI4i", {gl_backend_word(index), gl_backend_word(x), gl_backend_word(y), gl_backend_word(z), gl_backend_word(w)});
    }
    virtual void glVertexAttribI4iv(GLuint index, const GLint *v) {
        (void)invoke("glVertexAttribI4iv", {gl_backend_word(index), gl_backend_word(v)});
    }
    virtual void glVertexAttribI4ui(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w) {
        (void)invoke("glVertexAttribI4ui", {gl_backend_word(index), gl_backend_word(x), gl_backend_word(y), gl_backend_word(z), gl_backend_word(w)});
    }
    virtual void glVertexAttribI4uiv(GLuint index, const GLuint *v) {
        (void)invoke("glVertexAttribI4uiv", {gl_backend_word(index), gl_backend_word(v)});
    }
    virtual void glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer) {
        (void)invoke("glVertexAttribIPointer", {gl_backend_word(index), gl_backend_word(size), gl_backend_word(type), gl_backend_word(stride), gl_backend_word(pointer)});
    }
    virtual void glWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
        (void)invoke("glWaitSync", {gl_backend_word(sync), gl_backend_word(flags), gl_backend_word(timeout)});
    }
    virtual void glRenderbufferStorageMultisampleEXT(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height) {
        (void)invoke("glRenderbufferStorageMultisampleEXT", {gl_backend_word(target), gl_backend_word(samples), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual void glFramebufferTexture2DMultisampleEXT(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLsizei samples) {
        (void)invoke("glFramebufferTexture2DMultisampleEXT", {gl_backend_word(target), gl_backend_word(attachment), gl_backend_word(textarget), gl_backend_word(texture), gl_backend_word(level), gl_backend_word(samples)});
    }
    virtual void glDiscardFramebufferEXT(GLenum target, GLsizei numAttachments, const GLenum *attachments) {
        (void)invoke("glDiscardFramebufferEXT", {gl_backend_word(target), gl_backend_word(numAttachments), gl_backend_word(attachments)});
    }
    virtual void glBindVertexArrayOES(GLuint array) {
        (void)invoke("glBindVertexArrayOES", {gl_backend_word(array)});
    }
    virtual void glDeleteVertexArraysOES(GLsizei n, const GLuint *arrays) {
        (void)invoke("glDeleteVertexArraysOES", {gl_backend_word(n), gl_backend_word(arrays)});
    }
    virtual void glGenVertexArraysOES(GLsizei n, GLuint *arrays) {
        (void)invoke("glGenVertexArraysOES", {gl_backend_word(n), gl_backend_word(arrays)});
    }
    virtual GLboolean glIsVertexArrayOES(GLuint array) {
        return static_cast<GLboolean>(invoke("glIsVertexArrayOES", {gl_backend_word(array)}));
    }
    virtual void * glMapBufferOES(GLenum target, GLenum access) {
        return reinterpret_cast<void *>(static_cast<std::uintptr_t>(invoke("glMapBufferOES", {gl_backend_word(target), gl_backend_word(access)})));
    }
    virtual GLboolean glUnmapBufferOES(GLenum target) {
        return static_cast<GLboolean>(invoke("glUnmapBufferOES", {gl_backend_word(target)}));
    }
    virtual void glGetBufferPointervOES(GLenum target, GLenum pname, void **params) {
        (void)invoke("glGetBufferPointervOES", {gl_backend_word(target), gl_backend_word(pname), gl_backend_word(params)});
    }
    virtual void glTexStorage2DEXT(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height) {
        (void)invoke("glTexStorage2DEXT", {gl_backend_word(target), gl_backend_word(levels), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height)});
    }
    virtual void glTexStorage3DEXT(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth) {
        (void)invoke("glTexStorage3DEXT", {gl_backend_word(target), gl_backend_word(levels), gl_backend_word(internalformat), gl_backend_word(width), gl_backend_word(height), gl_backend_word(depth)});
    }
    virtual void glDebugMessageControlKHR(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled) {
        (void)invoke("glDebugMessageControlKHR", {gl_backend_word(source), gl_backend_word(type), gl_backend_word(severity), gl_backend_word(count), gl_backend_word(ids), gl_backend_word(enabled)});
    }
    virtual void glDebugMessageInsertKHR(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf) {
        (void)invoke("glDebugMessageInsertKHR", {gl_backend_word(source), gl_backend_word(type), gl_backend_word(id), gl_backend_word(severity), gl_backend_word(length), gl_backend_word(buf)});
    }
    virtual void glPushDebugGroupKHR(GLenum source, GLuint id, GLsizei length, const GLchar *message) {
        (void)invoke("glPushDebugGroupKHR", {gl_backend_word(source), gl_backend_word(id), gl_backend_word(length), gl_backend_word(message)});
    }
    virtual void glPopDebugGroupKHR(void) {
        (void)invoke("glPopDebugGroupKHR", {});
    }
    virtual void glObjectLabelKHR(GLenum identifier, GLuint name, GLsizei length, const GLchar *label) {
        (void)invoke("glObjectLabelKHR", {gl_backend_word(identifier), gl_backend_word(name), gl_backend_word(length), gl_backend_word(label)});
    }
    virtual void glGetObjectLabelKHR(GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label) {
        (void)invoke("glGetObjectLabelKHR", {gl_backend_word(identifier), gl_backend_word(name), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(label)});
    }
    virtual void glPushGroupMarkerEXT(GLsizei length, const GLchar *marker) {
        (void)invoke("glPushGroupMarkerEXT", {gl_backend_word(length), gl_backend_word(marker)});
    }
    virtual void glPopGroupMarkerEXT(void) {
        (void)invoke("glPopGroupMarkerEXT", {});
    }
    virtual void glLabelObjectEXT(GLenum type, GLuint object, GLsizei length, const GLchar *label) {
        (void)invoke("glLabelObjectEXT", {gl_backend_word(type), gl_backend_word(object), gl_backend_word(length), gl_backend_word(label)});
    }
    virtual void glGetObjectLabelEXT(GLenum type, GLuint object, GLsizei bufSize, GLsizei *length, GLchar *label) {
        (void)invoke("glGetObjectLabelEXT", {gl_backend_word(type), gl_backend_word(object), gl_backend_word(bufSize), gl_backend_word(length), gl_backend_word(label)});
    }

protected:
    virtual std::uint64_t invoke(const char* name,
                                 std::initializer_list<std::uint64_t> arguments) = 0;
};

}  // namespace zb
