// Generated by tools/gen_gles.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace zb {

// Three blocks: GLES 2.0 at 0-141, then GLES 3.0 and the curated extension entry
// points, both appended after every other stub library so no established host-call
// index moved.
inline constexpr std::uint32_t kGlHostCallFirst = 0;
inline constexpr std::uint32_t kGlHostCallLast = 141u;
inline constexpr std::size_t kGlHostCallCount = 142u;
inline constexpr std::uint32_t kGlHostCall3First = 228u;
inline constexpr std::uint32_t kGlHostCall3Last = 331u;
inline constexpr std::size_t kGlHostCall3Count = 104u;
inline constexpr std::uint32_t kGlHostCallExtFirst = 332u;
inline constexpr std::uint32_t kGlHostCallExtLast = 353u;
inline constexpr std::size_t kGlHostCallExtCount = 22u;
inline constexpr std::size_t kGlHostCallTotalCount = 268u;
inline constexpr std::size_t kGlPointerlessHostCallCount = 136u;

inline constexpr std::uint32_t ZB_GL_HC_glActiveTexture = 0u;
inline constexpr std::uint32_t ZB_GL_HC_glAttachShader = 1u;
inline constexpr std::uint32_t ZB_GL_HC_glBindAttribLocation = 2u;
inline constexpr std::uint32_t ZB_GL_HC_glBindBuffer = 3u;
inline constexpr std::uint32_t ZB_GL_HC_glBindFramebuffer = 4u;
inline constexpr std::uint32_t ZB_GL_HC_glBindRenderbuffer = 5u;
inline constexpr std::uint32_t ZB_GL_HC_glBindTexture = 6u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendColor = 7u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendEquation = 8u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendEquationSeparate = 9u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendFunc = 10u;
inline constexpr std::uint32_t ZB_GL_HC_glBlendFuncSeparate = 11u;
inline constexpr std::uint32_t ZB_GL_HC_glBufferData = 12u;
inline constexpr std::uint32_t ZB_GL_HC_glBufferSubData = 13u;
inline constexpr std::uint32_t ZB_GL_HC_glCheckFramebufferStatus = 14u;
inline constexpr std::uint32_t ZB_GL_HC_glClear = 15u;
inline constexpr std::uint32_t ZB_GL_HC_glClearColor = 16u;
inline constexpr std::uint32_t ZB_GL_HC_glClearDepthf = 17u;
inline constexpr std::uint32_t ZB_GL_HC_glClearStencil = 18u;
inline constexpr std::uint32_t ZB_GL_HC_glColorMask = 19u;
inline constexpr std::uint32_t ZB_GL_HC_glCompileShader = 20u;
inline constexpr std::uint32_t ZB_GL_HC_glCompressedTexImage2D = 21u;
inline constexpr std::uint32_t ZB_GL_HC_glCompressedTexSubImage2D = 22u;
inline constexpr std::uint32_t ZB_GL_HC_glCopyTexImage2D = 23u;
inline constexpr std::uint32_t ZB_GL_HC_glCopyTexSubImage2D = 24u;
inline constexpr std::uint32_t ZB_GL_HC_glCreateProgram = 25u;
inline constexpr std::uint32_t ZB_GL_HC_glCreateShader = 26u;
inline constexpr std::uint32_t ZB_GL_HC_glCullFace = 27u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteBuffers = 28u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteFramebuffers = 29u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteProgram = 30u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteRenderbuffers = 31u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteShader = 32u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteTextures = 33u;
inline constexpr std::uint32_t ZB_GL_HC_glDepthFunc = 34u;
inline constexpr std::uint32_t ZB_GL_HC_glDepthMask = 35u;
inline constexpr std::uint32_t ZB_GL_HC_glDepthRangef = 36u;
inline constexpr std::uint32_t ZB_GL_HC_glDetachShader = 37u;
inline constexpr std::uint32_t ZB_GL_HC_glDisable = 38u;
inline constexpr std::uint32_t ZB_GL_HC_glDisableVertexAttribArray = 39u;
inline constexpr std::uint32_t ZB_GL_HC_glDrawArrays = 40u;
inline constexpr std::uint32_t ZB_GL_HC_glDrawElements = 41u;
inline constexpr std::uint32_t ZB_GL_HC_glEnable = 42u;
inline constexpr std::uint32_t ZB_GL_HC_glEnableVertexAttribArray = 43u;
inline constexpr std::uint32_t ZB_GL_HC_glFinish = 44u;
inline constexpr std::uint32_t ZB_GL_HC_glFlush = 45u;
inline constexpr std::uint32_t ZB_GL_HC_glFramebufferRenderbuffer = 46u;
inline constexpr std::uint32_t ZB_GL_HC_glFramebufferTexture2D = 47u;
inline constexpr std::uint32_t ZB_GL_HC_glFrontFace = 48u;
inline constexpr std::uint32_t ZB_GL_HC_glGenBuffers = 49u;
inline constexpr std::uint32_t ZB_GL_HC_glGenFramebuffers = 50u;
inline constexpr std::uint32_t ZB_GL_HC_glGenRenderbuffers = 51u;
inline constexpr std::uint32_t ZB_GL_HC_glGenTextures = 52u;
inline constexpr std::uint32_t ZB_GL_HC_glGenerateMipmap = 53u;
inline constexpr std::uint32_t ZB_GL_HC_glGetActiveAttrib = 54u;
inline constexpr std::uint32_t ZB_GL_HC_glGetActiveUniform = 55u;
inline constexpr std::uint32_t ZB_GL_HC_glGetAttachedShaders = 56u;
inline constexpr std::uint32_t ZB_GL_HC_glGetAttribLocation = 57u;
inline constexpr std::uint32_t ZB_GL_HC_glGetBooleanv = 58u;
inline constexpr std::uint32_t ZB_GL_HC_glGetBufferParameteriv = 59u;
inline constexpr std::uint32_t ZB_GL_HC_glGetError = 60u;
inline constexpr std::uint32_t ZB_GL_HC_glGetFloatv = 61u;
inline constexpr std::uint32_t ZB_GL_HC_glGetFramebufferAttachmentParameteriv = 62u;
inline constexpr std::uint32_t ZB_GL_HC_glGetIntegerv = 63u;
inline constexpr std::uint32_t ZB_GL_HC_glGetProgramInfoLog = 64u;
inline constexpr std::uint32_t ZB_GL_HC_glGetProgramiv = 65u;
inline constexpr std::uint32_t ZB_GL_HC_glGetRenderbufferParameteriv = 66u;
inline constexpr std::uint32_t ZB_GL_HC_glGetShaderInfoLog = 67u;
inline constexpr std::uint32_t ZB_GL_HC_glGetShaderPrecisionFormat = 68u;
inline constexpr std::uint32_t ZB_GL_HC_glGetShaderSource = 69u;
inline constexpr std::uint32_t ZB_GL_HC_glGetShaderiv = 70u;
inline constexpr std::uint32_t ZB_GL_HC_glGetString = 71u;
inline constexpr std::uint32_t ZB_GL_HC_glGetTexParameterfv = 72u;
inline constexpr std::uint32_t ZB_GL_HC_glGetTexParameteriv = 73u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformLocation = 74u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformfv = 75u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformiv = 76u;
inline constexpr std::uint32_t ZB_GL_HC_glGetVertexAttribPointerv = 77u;
inline constexpr std::uint32_t ZB_GL_HC_glGetVertexAttribfv = 78u;
inline constexpr std::uint32_t ZB_GL_HC_glGetVertexAttribiv = 79u;
inline constexpr std::uint32_t ZB_GL_HC_glHint = 80u;
inline constexpr std::uint32_t ZB_GL_HC_glIsBuffer = 81u;
inline constexpr std::uint32_t ZB_GL_HC_glIsEnabled = 82u;
inline constexpr std::uint32_t ZB_GL_HC_glIsFramebuffer = 83u;
inline constexpr std::uint32_t ZB_GL_HC_glIsProgram = 84u;
inline constexpr std::uint32_t ZB_GL_HC_glIsRenderbuffer = 85u;
inline constexpr std::uint32_t ZB_GL_HC_glIsShader = 86u;
inline constexpr std::uint32_t ZB_GL_HC_glIsTexture = 87u;
inline constexpr std::uint32_t ZB_GL_HC_glLineWidth = 88u;
inline constexpr std::uint32_t ZB_GL_HC_glLinkProgram = 89u;
inline constexpr std::uint32_t ZB_GL_HC_glPixelStorei = 90u;
inline constexpr std::uint32_t ZB_GL_HC_glPolygonOffset = 91u;
inline constexpr std::uint32_t ZB_GL_HC_glReadPixels = 92u;
inline constexpr std::uint32_t ZB_GL_HC_glReleaseShaderCompiler = 93u;
inline constexpr std::uint32_t ZB_GL_HC_glRenderbufferStorage = 94u;
inline constexpr std::uint32_t ZB_GL_HC_glSampleCoverage = 95u;
inline constexpr std::uint32_t ZB_GL_HC_glScissor = 96u;
inline constexpr std::uint32_t ZB_GL_HC_glShaderBinary = 97u;
inline constexpr std::uint32_t ZB_GL_HC_glShaderSource = 98u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilFunc = 99u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilFuncSeparate = 100u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilMask = 101u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilMaskSeparate = 102u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilOp = 103u;
inline constexpr std::uint32_t ZB_GL_HC_glStencilOpSeparate = 104u;
inline constexpr std::uint32_t ZB_GL_HC_glTexImage2D = 105u;
inline constexpr std::uint32_t ZB_GL_HC_glTexParameterf = 106u;
inline constexpr std::uint32_t ZB_GL_HC_glTexParameterfv = 107u;
inline constexpr std::uint32_t ZB_GL_HC_glTexParameteri = 108u;
inline constexpr std::uint32_t ZB_GL_HC_glTexParameteriv = 109u;
inline constexpr std::uint32_t ZB_GL_HC_glTexSubImage2D = 110u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1f = 111u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1fv = 112u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1i = 113u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1iv = 114u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2f = 115u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2fv = 116u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2i = 117u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2iv = 118u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3f = 119u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3fv = 120u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3i = 121u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3iv = 122u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4f = 123u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4fv = 124u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4i = 125u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4iv = 126u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix2fv = 127u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix3fv = 128u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix4fv = 129u;
inline constexpr std::uint32_t ZB_GL_HC_glUseProgram = 130u;
inline constexpr std::uint32_t ZB_GL_HC_glValidateProgram = 131u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib1f = 132u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib1fv = 133u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib2f = 134u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib2fv = 135u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib3f = 136u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib3fv = 137u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib4f = 138u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttrib4fv = 139u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttribPointer = 140u;
inline constexpr std::uint32_t ZB_GL_HC_glViewport = 141u;
inline constexpr std::uint32_t ZB_GL_HC_glBeginQuery = 228u;
inline constexpr std::uint32_t ZB_GL_HC_glBeginTransformFeedback = 229u;
inline constexpr std::uint32_t ZB_GL_HC_glBindBufferBase = 230u;
inline constexpr std::uint32_t ZB_GL_HC_glBindBufferRange = 231u;
inline constexpr std::uint32_t ZB_GL_HC_glBindSampler = 232u;
inline constexpr std::uint32_t ZB_GL_HC_glBindTransformFeedback = 233u;
inline constexpr std::uint32_t ZB_GL_HC_glBindVertexArray = 234u;
inline constexpr std::uint32_t ZB_GL_HC_glBlitFramebuffer = 235u;
inline constexpr std::uint32_t ZB_GL_HC_glClearBufferfi = 236u;
inline constexpr std::uint32_t ZB_GL_HC_glClearBufferfv = 237u;
inline constexpr std::uint32_t ZB_GL_HC_glClearBufferiv = 238u;
inline constexpr std::uint32_t ZB_GL_HC_glClearBufferuiv = 239u;
inline constexpr std::uint32_t ZB_GL_HC_glClientWaitSync = 240u;
inline constexpr std::uint32_t ZB_GL_HC_glCompressedTexImage3D = 241u;
inline constexpr std::uint32_t ZB_GL_HC_glCompressedTexSubImage3D = 242u;
inline constexpr std::uint32_t ZB_GL_HC_glCopyBufferSubData = 243u;
inline constexpr std::uint32_t ZB_GL_HC_glCopyTexSubImage3D = 244u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteQueries = 245u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteSamplers = 246u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteSync = 247u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteTransformFeedbacks = 248u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteVertexArrays = 249u;
inline constexpr std::uint32_t ZB_GL_HC_glDrawArraysInstanced = 250u;
inline constexpr std::uint32_t ZB_GL_HC_glDrawBuffers = 251u;
inline constexpr std::uint32_t ZB_GL_HC_glDrawElementsInstanced = 252u;
inline constexpr std::uint32_t ZB_GL_HC_glDrawRangeElements = 253u;
inline constexpr std::uint32_t ZB_GL_HC_glEndQuery = 254u;
inline constexpr std::uint32_t ZB_GL_HC_glEndTransformFeedback = 255u;
inline constexpr std::uint32_t ZB_GL_HC_glFenceSync = 256u;
inline constexpr std::uint32_t ZB_GL_HC_glFlushMappedBufferRange = 257u;
inline constexpr std::uint32_t ZB_GL_HC_glFramebufferTextureLayer = 258u;
inline constexpr std::uint32_t ZB_GL_HC_glGenQueries = 259u;
inline constexpr std::uint32_t ZB_GL_HC_glGenSamplers = 260u;
inline constexpr std::uint32_t ZB_GL_HC_glGenTransformFeedbacks = 261u;
inline constexpr std::uint32_t ZB_GL_HC_glGenVertexArrays = 262u;
inline constexpr std::uint32_t ZB_GL_HC_glGetActiveUniformBlockName = 263u;
inline constexpr std::uint32_t ZB_GL_HC_glGetActiveUniformBlockiv = 264u;
inline constexpr std::uint32_t ZB_GL_HC_glGetActiveUniformsiv = 265u;
inline constexpr std::uint32_t ZB_GL_HC_glGetBufferParameteri64v = 266u;
inline constexpr std::uint32_t ZB_GL_HC_glGetBufferPointerv = 267u;
inline constexpr std::uint32_t ZB_GL_HC_glGetFragDataLocation = 268u;
inline constexpr std::uint32_t ZB_GL_HC_glGetInteger64i_v = 269u;
inline constexpr std::uint32_t ZB_GL_HC_glGetInteger64v = 270u;
inline constexpr std::uint32_t ZB_GL_HC_glGetIntegeri_v = 271u;
inline constexpr std::uint32_t ZB_GL_HC_glGetInternalformativ = 272u;
inline constexpr std::uint32_t ZB_GL_HC_glGetProgramBinary = 273u;
inline constexpr std::uint32_t ZB_GL_HC_glGetQueryObjectuiv = 274u;
inline constexpr std::uint32_t ZB_GL_HC_glGetQueryiv = 275u;
inline constexpr std::uint32_t ZB_GL_HC_glGetSamplerParameterfv = 276u;
inline constexpr std::uint32_t ZB_GL_HC_glGetSamplerParameteriv = 277u;
inline constexpr std::uint32_t ZB_GL_HC_glGetStringi = 278u;
inline constexpr std::uint32_t ZB_GL_HC_glGetSynciv = 279u;
inline constexpr std::uint32_t ZB_GL_HC_glGetTransformFeedbackVarying = 280u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformBlockIndex = 281u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformIndices = 282u;
inline constexpr std::uint32_t ZB_GL_HC_glGetUniformuiv = 283u;
inline constexpr std::uint32_t ZB_GL_HC_glGetVertexAttribIiv = 284u;
inline constexpr std::uint32_t ZB_GL_HC_glGetVertexAttribIuiv = 285u;
inline constexpr std::uint32_t ZB_GL_HC_glInvalidateFramebuffer = 286u;
inline constexpr std::uint32_t ZB_GL_HC_glInvalidateSubFramebuffer = 287u;
inline constexpr std::uint32_t ZB_GL_HC_glIsQuery = 288u;
inline constexpr std::uint32_t ZB_GL_HC_glIsSampler = 289u;
inline constexpr std::uint32_t ZB_GL_HC_glIsSync = 290u;
inline constexpr std::uint32_t ZB_GL_HC_glIsTransformFeedback = 291u;
inline constexpr std::uint32_t ZB_GL_HC_glIsVertexArray = 292u;
inline constexpr std::uint32_t ZB_GL_HC_glMapBufferRange = 293u;
inline constexpr std::uint32_t ZB_GL_HC_glPauseTransformFeedback = 294u;
inline constexpr std::uint32_t ZB_GL_HC_glProgramBinary = 295u;
inline constexpr std::uint32_t ZB_GL_HC_glProgramParameteri = 296u;
inline constexpr std::uint32_t ZB_GL_HC_glReadBuffer = 297u;
inline constexpr std::uint32_t ZB_GL_HC_glRenderbufferStorageMultisample = 298u;
inline constexpr std::uint32_t ZB_GL_HC_glResumeTransformFeedback = 299u;
inline constexpr std::uint32_t ZB_GL_HC_glSamplerParameterf = 300u;
inline constexpr std::uint32_t ZB_GL_HC_glSamplerParameterfv = 301u;
inline constexpr std::uint32_t ZB_GL_HC_glSamplerParameteri = 302u;
inline constexpr std::uint32_t ZB_GL_HC_glSamplerParameteriv = 303u;
inline constexpr std::uint32_t ZB_GL_HC_glTexImage3D = 304u;
inline constexpr std::uint32_t ZB_GL_HC_glTexStorage2D = 305u;
inline constexpr std::uint32_t ZB_GL_HC_glTexStorage3D = 306u;
inline constexpr std::uint32_t ZB_GL_HC_glTexSubImage3D = 307u;
inline constexpr std::uint32_t ZB_GL_HC_glTransformFeedbackVaryings = 308u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1ui = 309u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform1uiv = 310u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2ui = 311u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform2uiv = 312u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3ui = 313u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform3uiv = 314u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4ui = 315u;
inline constexpr std::uint32_t ZB_GL_HC_glUniform4uiv = 316u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformBlockBinding = 317u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix2x3fv = 318u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix2x4fv = 319u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix3x2fv = 320u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix3x4fv = 321u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix4x2fv = 322u;
inline constexpr std::uint32_t ZB_GL_HC_glUniformMatrix4x3fv = 323u;
inline constexpr std::uint32_t ZB_GL_HC_glUnmapBuffer = 324u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttribDivisor = 325u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttribI4i = 326u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttribI4iv = 327u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttribI4ui = 328u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttribI4uiv = 329u;
inline constexpr std::uint32_t ZB_GL_HC_glVertexAttribIPointer = 330u;
inline constexpr std::uint32_t ZB_GL_HC_glWaitSync = 331u;
inline constexpr std::uint32_t ZB_GL_HC_glRenderbufferStorageMultisampleEXT = 332u;
inline constexpr std::uint32_t ZB_GL_HC_glFramebufferTexture2DMultisampleEXT = 333u;
inline constexpr std::uint32_t ZB_GL_HC_glDiscardFramebufferEXT = 334u;
inline constexpr std::uint32_t ZB_GL_HC_glBindVertexArrayOES = 335u;
inline constexpr std::uint32_t ZB_GL_HC_glDeleteVertexArraysOES = 336u;
inline constexpr std::uint32_t ZB_GL_HC_glGenVertexArraysOES = 337u;
inline constexpr std::uint32_t ZB_GL_HC_glIsVertexArrayOES = 338u;
inline constexpr std::uint32_t ZB_GL_HC_glMapBufferOES = 339u;
inline constexpr std::uint32_t ZB_GL_HC_glUnmapBufferOES = 340u;
inline constexpr std::uint32_t ZB_GL_HC_glGetBufferPointervOES = 341u;
inline constexpr std::uint32_t ZB_GL_HC_glTexStorage2DEXT = 342u;
inline constexpr std::uint32_t ZB_GL_HC_glTexStorage3DEXT = 343u;
inline constexpr std::uint32_t ZB_GL_HC_glDebugMessageControlKHR = 344u;
inline constexpr std::uint32_t ZB_GL_HC_glDebugMessageInsertKHR = 345u;
inline constexpr std::uint32_t ZB_GL_HC_glPushDebugGroupKHR = 346u;
inline constexpr std::uint32_t ZB_GL_HC_glPopDebugGroupKHR = 347u;
inline constexpr std::uint32_t ZB_GL_HC_glObjectLabelKHR = 348u;
inline constexpr std::uint32_t ZB_GL_HC_glGetObjectLabelKHR = 349u;
inline constexpr std::uint32_t ZB_GL_HC_glPushGroupMarkerEXT = 350u;
inline constexpr std::uint32_t ZB_GL_HC_glPopGroupMarkerEXT = 351u;
inline constexpr std::uint32_t ZB_GL_HC_glLabelObjectEXT = 352u;
inline constexpr std::uint32_t ZB_GL_HC_glGetObjectLabelEXT = 353u;

struct GlHostCallInfo {
    std::uint32_t index;
    const char* name;
    bool has_pointer;
};

// GLES 2.0 first, then GLES 3.0, then the extensions; use gl_host_call() rather than
// indexing by host call.
inline constexpr std::array<GlHostCallInfo, kGlHostCallTotalCount> kGlHostCalls{{
    {0u, "glActiveTexture", false},
    {1u, "glAttachShader", false},
    {2u, "glBindAttribLocation", true},
    {3u, "glBindBuffer", false},
    {4u, "glBindFramebuffer", false},
    {5u, "glBindRenderbuffer", false},
    {6u, "glBindTexture", false},
    {7u, "glBlendColor", false},
    {8u, "glBlendEquation", false},
    {9u, "glBlendEquationSeparate", false},
    {10u, "glBlendFunc", false},
    {11u, "glBlendFuncSeparate", false},
    {12u, "glBufferData", true},
    {13u, "glBufferSubData", true},
    {14u, "glCheckFramebufferStatus", false},
    {15u, "glClear", false},
    {16u, "glClearColor", false},
    {17u, "glClearDepthf", false},
    {18u, "glClearStencil", false},
    {19u, "glColorMask", false},
    {20u, "glCompileShader", false},
    {21u, "glCompressedTexImage2D", true},
    {22u, "glCompressedTexSubImage2D", true},
    {23u, "glCopyTexImage2D", false},
    {24u, "glCopyTexSubImage2D", false},
    {25u, "glCreateProgram", false},
    {26u, "glCreateShader", false},
    {27u, "glCullFace", false},
    {28u, "glDeleteBuffers", true},
    {29u, "glDeleteFramebuffers", true},
    {30u, "glDeleteProgram", false},
    {31u, "glDeleteRenderbuffers", true},
    {32u, "glDeleteShader", false},
    {33u, "glDeleteTextures", true},
    {34u, "glDepthFunc", false},
    {35u, "glDepthMask", false},
    {36u, "glDepthRangef", false},
    {37u, "glDetachShader", false},
    {38u, "glDisable", false},
    {39u, "glDisableVertexAttribArray", false},
    {40u, "glDrawArrays", false},
    {41u, "glDrawElements", true},
    {42u, "glEnable", false},
    {43u, "glEnableVertexAttribArray", false},
    {44u, "glFinish", false},
    {45u, "glFlush", false},
    {46u, "glFramebufferRenderbuffer", false},
    {47u, "glFramebufferTexture2D", false},
    {48u, "glFrontFace", false},
    {49u, "glGenBuffers", true},
    {50u, "glGenFramebuffers", true},
    {51u, "glGenRenderbuffers", true},
    {52u, "glGenTextures", true},
    {53u, "glGenerateMipmap", false},
    {54u, "glGetActiveAttrib", true},
    {55u, "glGetActiveUniform", true},
    {56u, "glGetAttachedShaders", true},
    {57u, "glGetAttribLocation", true},
    {58u, "glGetBooleanv", true},
    {59u, "glGetBufferParameteriv", true},
    {60u, "glGetError", false},
    {61u, "glGetFloatv", true},
    {62u, "glGetFramebufferAttachmentParameteriv", true},
    {63u, "glGetIntegerv", true},
    {64u, "glGetProgramInfoLog", true},
    {65u, "glGetProgramiv", true},
    {66u, "glGetRenderbufferParameteriv", true},
    {67u, "glGetShaderInfoLog", true},
    {68u, "glGetShaderPrecisionFormat", true},
    {69u, "glGetShaderSource", true},
    {70u, "glGetShaderiv", true},
    {71u, "glGetString", false},
    {72u, "glGetTexParameterfv", true},
    {73u, "glGetTexParameteriv", true},
    {74u, "glGetUniformLocation", true},
    {75u, "glGetUniformfv", true},
    {76u, "glGetUniformiv", true},
    {77u, "glGetVertexAttribPointerv", true},
    {78u, "glGetVertexAttribfv", true},
    {79u, "glGetVertexAttribiv", true},
    {80u, "glHint", false},
    {81u, "glIsBuffer", false},
    {82u, "glIsEnabled", false},
    {83u, "glIsFramebuffer", false},
    {84u, "glIsProgram", false},
    {85u, "glIsRenderbuffer", false},
    {86u, "glIsShader", false},
    {87u, "glIsTexture", false},
    {88u, "glLineWidth", false},
    {89u, "glLinkProgram", false},
    {90u, "glPixelStorei", false},
    {91u, "glPolygonOffset", false},
    {92u, "glReadPixels", true},
    {93u, "glReleaseShaderCompiler", false},
    {94u, "glRenderbufferStorage", false},
    {95u, "glSampleCoverage", false},
    {96u, "glScissor", false},
    {97u, "glShaderBinary", true},
    {98u, "glShaderSource", true},
    {99u, "glStencilFunc", false},
    {100u, "glStencilFuncSeparate", false},
    {101u, "glStencilMask", false},
    {102u, "glStencilMaskSeparate", false},
    {103u, "glStencilOp", false},
    {104u, "glStencilOpSeparate", false},
    {105u, "glTexImage2D", true},
    {106u, "glTexParameterf", false},
    {107u, "glTexParameterfv", true},
    {108u, "glTexParameteri", false},
    {109u, "glTexParameteriv", true},
    {110u, "glTexSubImage2D", true},
    {111u, "glUniform1f", false},
    {112u, "glUniform1fv", true},
    {113u, "glUniform1i", false},
    {114u, "glUniform1iv", true},
    {115u, "glUniform2f", false},
    {116u, "glUniform2fv", true},
    {117u, "glUniform2i", false},
    {118u, "glUniform2iv", true},
    {119u, "glUniform3f", false},
    {120u, "glUniform3fv", true},
    {121u, "glUniform3i", false},
    {122u, "glUniform3iv", true},
    {123u, "glUniform4f", false},
    {124u, "glUniform4fv", true},
    {125u, "glUniform4i", false},
    {126u, "glUniform4iv", true},
    {127u, "glUniformMatrix2fv", true},
    {128u, "glUniformMatrix3fv", true},
    {129u, "glUniformMatrix4fv", true},
    {130u, "glUseProgram", false},
    {131u, "glValidateProgram", false},
    {132u, "glVertexAttrib1f", false},
    {133u, "glVertexAttrib1fv", true},
    {134u, "glVertexAttrib2f", false},
    {135u, "glVertexAttrib2fv", true},
    {136u, "glVertexAttrib3f", false},
    {137u, "glVertexAttrib3fv", true},
    {138u, "glVertexAttrib4f", false},
    {139u, "glVertexAttrib4fv", true},
    {140u, "glVertexAttribPointer", true},
    {141u, "glViewport", false},
    {228u, "glBeginQuery", false},
    {229u, "glBeginTransformFeedback", false},
    {230u, "glBindBufferBase", false},
    {231u, "glBindBufferRange", false},
    {232u, "glBindSampler", false},
    {233u, "glBindTransformFeedback", false},
    {234u, "glBindVertexArray", false},
    {235u, "glBlitFramebuffer", false},
    {236u, "glClearBufferfi", false},
    {237u, "glClearBufferfv", true},
    {238u, "glClearBufferiv", true},
    {239u, "glClearBufferuiv", true},
    {240u, "glClientWaitSync", false},
    {241u, "glCompressedTexImage3D", true},
    {242u, "glCompressedTexSubImage3D", true},
    {243u, "glCopyBufferSubData", false},
    {244u, "glCopyTexSubImage3D", false},
    {245u, "glDeleteQueries", true},
    {246u, "glDeleteSamplers", true},
    {247u, "glDeleteSync", false},
    {248u, "glDeleteTransformFeedbacks", true},
    {249u, "glDeleteVertexArrays", true},
    {250u, "glDrawArraysInstanced", false},
    {251u, "glDrawBuffers", true},
    {252u, "glDrawElementsInstanced", true},
    {253u, "glDrawRangeElements", true},
    {254u, "glEndQuery", false},
    {255u, "glEndTransformFeedback", false},
    {256u, "glFenceSync", false},
    {257u, "glFlushMappedBufferRange", false},
    {258u, "glFramebufferTextureLayer", false},
    {259u, "glGenQueries", true},
    {260u, "glGenSamplers", true},
    {261u, "glGenTransformFeedbacks", true},
    {262u, "glGenVertexArrays", true},
    {263u, "glGetActiveUniformBlockName", true},
    {264u, "glGetActiveUniformBlockiv", true},
    {265u, "glGetActiveUniformsiv", true},
    {266u, "glGetBufferParameteri64v", true},
    {267u, "glGetBufferPointerv", true},
    {268u, "glGetFragDataLocation", true},
    {269u, "glGetInteger64i_v", true},
    {270u, "glGetInteger64v", true},
    {271u, "glGetIntegeri_v", true},
    {272u, "glGetInternalformativ", true},
    {273u, "glGetProgramBinary", true},
    {274u, "glGetQueryObjectuiv", true},
    {275u, "glGetQueryiv", true},
    {276u, "glGetSamplerParameterfv", true},
    {277u, "glGetSamplerParameteriv", true},
    {278u, "glGetStringi", false},
    {279u, "glGetSynciv", true},
    {280u, "glGetTransformFeedbackVarying", true},
    {281u, "glGetUniformBlockIndex", true},
    {282u, "glGetUniformIndices", true},
    {283u, "glGetUniformuiv", true},
    {284u, "glGetVertexAttribIiv", true},
    {285u, "glGetVertexAttribIuiv", true},
    {286u, "glInvalidateFramebuffer", true},
    {287u, "glInvalidateSubFramebuffer", true},
    {288u, "glIsQuery", false},
    {289u, "glIsSampler", false},
    {290u, "glIsSync", false},
    {291u, "glIsTransformFeedback", false},
    {292u, "glIsVertexArray", false},
    {293u, "glMapBufferRange", false},
    {294u, "glPauseTransformFeedback", false},
    {295u, "glProgramBinary", true},
    {296u, "glProgramParameteri", false},
    {297u, "glReadBuffer", false},
    {298u, "glRenderbufferStorageMultisample", false},
    {299u, "glResumeTransformFeedback", false},
    {300u, "glSamplerParameterf", false},
    {301u, "glSamplerParameterfv", true},
    {302u, "glSamplerParameteri", false},
    {303u, "glSamplerParameteriv", true},
    {304u, "glTexImage3D", true},
    {305u, "glTexStorage2D", false},
    {306u, "glTexStorage3D", false},
    {307u, "glTexSubImage3D", true},
    {308u, "glTransformFeedbackVaryings", true},
    {309u, "glUniform1ui", false},
    {310u, "glUniform1uiv", true},
    {311u, "glUniform2ui", false},
    {312u, "glUniform2uiv", true},
    {313u, "glUniform3ui", false},
    {314u, "glUniform3uiv", true},
    {315u, "glUniform4ui", false},
    {316u, "glUniform4uiv", true},
    {317u, "glUniformBlockBinding", false},
    {318u, "glUniformMatrix2x3fv", true},
    {319u, "glUniformMatrix2x4fv", true},
    {320u, "glUniformMatrix3x2fv", true},
    {321u, "glUniformMatrix3x4fv", true},
    {322u, "glUniformMatrix4x2fv", true},
    {323u, "glUniformMatrix4x3fv", true},
    {324u, "glUnmapBuffer", false},
    {325u, "glVertexAttribDivisor", false},
    {326u, "glVertexAttribI4i", false},
    {327u, "glVertexAttribI4iv", true},
    {328u, "glVertexAttribI4ui", false},
    {329u, "glVertexAttribI4uiv", true},
    {330u, "glVertexAttribIPointer", true},
    {331u, "glWaitSync", false},
    {332u, "glRenderbufferStorageMultisampleEXT", false},
    {333u, "glFramebufferTexture2DMultisampleEXT", false},
    {334u, "glDiscardFramebufferEXT", true},
    {335u, "glBindVertexArrayOES", false},
    {336u, "glDeleteVertexArraysOES", true},
    {337u, "glGenVertexArraysOES", true},
    {338u, "glIsVertexArrayOES", false},
    {339u, "glMapBufferOES", false},
    {340u, "glUnmapBufferOES", false},
    {341u, "glGetBufferPointervOES", true},
    {342u, "glTexStorage2DEXT", false},
    {343u, "glTexStorage3DEXT", false},
    {344u, "glDebugMessageControlKHR", true},
    {345u, "glDebugMessageInsertKHR", true},
    {346u, "glPushDebugGroupKHR", true},
    {347u, "glPopDebugGroupKHR", false},
    {348u, "glObjectLabelKHR", true},
    {349u, "glGetObjectLabelKHR", true},
    {350u, "glPushGroupMarkerEXT", true},
    {351u, "glPopGroupMarkerEXT", false},
    {352u, "glLabelObjectEXT", true},
    {353u, "glGetObjectLabelEXT", true},
}};

inline constexpr const GlHostCallInfo* gl_host_call(std::uint32_t index) {
    if (index <= kGlHostCallLast) return &kGlHostCalls[index];
    if (index >= kGlHostCall3First && index <= kGlHostCall3Last) {
        return &kGlHostCalls[kGlHostCallCount + (index - kGlHostCall3First)];
    }
    if (index >= kGlHostCallExtFirst && index <= kGlHostCallExtLast) {
        return &kGlHostCalls[kGlHostCallCount + kGlHostCall3Count +
                             (index - kGlHostCallExtFirst)];
    }
    return nullptr;
}

inline constexpr bool is_gl_host_call(std::uint32_t index) {
    return gl_host_call(index) != nullptr;
}

inline constexpr const char* gl_host_call_name(std::uint32_t index) {
    const GlHostCallInfo* info = gl_host_call(index);
    return info == nullptr ? "?" : info->name;
}

}  // namespace zb
