#!/usr/bin/env python3
"""Generate the GLES 2.0 + 3.0 + extension host-call protocol and dispatcher.

The Khronos registry copy was downloaded on 2026-09-16 from:
https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/main/xml/gl.xml

Inputs:
  third_party/registry/gl.xml                  pinned Khronos registry
  NDK sysroot/usr/include/GLES2/gl2.h          exported GLES 2.0 names
  NDK sysroot/usr/include/GLES3/gl3.h          the GLES 3.0 names gl2.h does not export
  core/src/gen/hostcalls.inc                   guest stub index assignment

The extension entry points come from gen_stubs.GLES_EXTENSIONS (names) plus gl.xml
(signatures); that list is the one place to touch to add an extension.

Outputs are committed. Run with --check to reject stale files.
"""

import os
import re
import sys
import xml.etree.ElementTree as ET

sys.dont_write_bytecode = True
import gen_stubs


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(ROOT, "third_party", "registry", "gl.xml")
HOSTCALLS = os.path.join(ROOT, "core", "src", "gen", "hostcalls.inc")
EXPECTED_GLES = 142
EXPECTED_GLES3 = 104
EXPECTED_EXT = 22
EXPECTED_POINTERLESS = 81
EXPECTED_GLES3_POINTERLESS = 45
EXPECTED_EXT_POINTERLESS = 10
EXPECTED_TASK3_MECHANICAL = 125
EXPECTED_GLES3_MECHANICAL = 76
EXPECTED_EXT_MECHANICAL = 13
HEADER = "Generated by tools/gen_gles.py. Do not edit."

# Semantic handlers from the approved design. glGetString is the important Task 1 exception:
# it has no pointer parameter, but its host-pointer return must never be copied into guest r0.
HANDWRITTEN = {
    "glDrawArrays",
    "glDrawElements",
    "glGetString",
    "glGetUniformfv",
    "glGetUniformiv",
    "glGetVertexAttribPointerv",
    "glReadPixels",
    "glShaderSource",
    "glTexImage2D",
    "glTexSubImage2D",
    "glVertexAttribPointer",
    # GLES 3.0. Same rule as above: a host pointer must never reach the guest, every guest
    # pointer is bounds-checked, and a length the registry only describes as COMPSIZE(...) is
    # resolved by hand. The sync entry points take and return a GLsync, which is a host pointer,
    # so they go through a 32-bit handle table in core/src/gl/gl_manual.cpp.
    "glClearBufferfv",
    "glClearBufferiv",
    "glClearBufferuiv",
    "glClientWaitSync",
    "glDeleteSync",
    "glDrawArraysInstanced",
    "glDrawElementsInstanced",
    "glDrawRangeElements",
    "glFenceSync",
    "glFlushMappedBufferRange",
    "glGetActiveUniformBlockiv",
    "glGetActiveUniformsiv",
    "glGetBufferPointerv",
    "glGetFragDataLocation",
    "glGetInteger64v",
    "glGetStringi",
    "glGetSynciv",
    "glGetUniformBlockIndex",
    "glGetUniformIndices",
    "glGetUniformuiv",
    "glIsSync",
    "glMapBufferRange",
    "glTexImage3D",
    "glTexSubImage3D",
    "glTransformFeedbackVaryings",
    "glUnmapBuffer",
    "glVertexAttribIPointer",
    "glWaitSync",
    # GLES extensions. glMapBufferOES has no pointer parameter but returns one, so it needs the
    # same guest mirror as glMapBufferRange; glUnmapBufferOES writes that mirror back, and
    # glGetBufferPointervOES reports the mirror address rather than the driver's pointer.
    "glGetBufferPointervOES",
    "glMapBufferOES",
    "glUnmapBufferOES",
}

TASK3_ONE_ELEMENT_COMPSIZE = {
    "glGetBufferParameteriv",
    "glGetFramebufferAttachmentParameteriv",
    "glGetProgramiv",
    "glGetRenderbufferParameteriv",
    "glGetShaderiv",
    "glGetTexParameterfv",
    "glGetTexParameteriv",
    "glTexParameterfv",
    "glTexParameteriv",
    # GLES 3.0: every pname these accept describes a single value.
    "glGetBufferParameteri64v",
    "glGetInteger64i_v",
    "glGetIntegeri_v",
    "glGetQueryObjectuiv",
    "glGetQueryiv",
    "glGetSamplerParameterfv",
    "glGetSamplerParameteriv",
    "glSamplerParameterfv",
    "glSamplerParameteriv",
}


class Parameter:
    def __init__(self, declaration, name, length):
        self.declaration = declaration
        self.name = name
        self.length = length

    @property
    def pointer(self):
        return "*" in self.declaration


class Command:
    def __init__(self, name, result, parameters):
        self.name = name
        self.result = result
        self.parameters = parameters

    @property
    def pointer(self):
        return any(parameter.pointer for parameter in self.parameters)


def pointer_pointee(parameter):
    prefix = parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()
    if prefix.count("*") != 1:
        return None
    return prefix[:prefix.rfind("*")].strip()


def length_rule(command, parameter):
    length = parameter.length
    if length in ("COMPSIZE(pname)", "COMPSIZE(target)") and \
            command.name in TASK3_ONE_ELEMENT_COMPSIZE:
        return (None, 1)
    if length is None or length.startswith("COMPSIZE"):
        return None
    if re.fullmatch(r"[1-4]", length):
        return (None, int(length))
    match = re.fullmatch(r"([A-Za-z_]\w*)(?:\*(\d+))?", length)
    if match is None:
        return None
    return (match.group(1), int(match.group(2) or "1"))


def mechanical(command):
    if command.name in HANDWRITTEN:
        return False
    return all(pointer_pointee(parameter) is not None and length_rule(command, parameter) is not None
               for parameter in command.parameters if parameter.pointer)


def element_text(element):
    return "".join(element.itertext()).strip()


def feature_names(root, feature, expected):
    node = root.find("./feature[@name='%s']" % feature)
    if node is None:
        sys.exit("gl.xml: %s not found" % feature)
    names = []
    for requirement in node.findall("require"):
        names.extend(child.get("name") for child in requirement.findall("command"))
    if len(names) != expected or len(set(names)) != expected:
        sys.exit("gl.xml: expected %d unique %s commands, got %d (%d unique)" %
                 (expected, feature, len(names), len(set(names))))
    return names


def extension_names(root):
    """The curated extension entry points, each checked against its <extension> block.

    gen_stubs.GLES_EXTENSIONS names them; gl.xml still owns every signature, and an entry point
    that its extension does not define (or a GLES-2 extension that is not one) fails here.
    """
    names = []
    for extension, wanted in gen_stubs.GLES_EXTENSIONS:
        node = root.find("./extensions/extension[@name='%s']" % extension)
        if node is None:
            sys.exit("gl.xml: extension %s not found" % extension)
        if "gles2" not in (node.get("supported") or "").split("|"):
            sys.exit("gl.xml: %s is not supported on gles2" % extension)
        defined = set()
        for requirement in node.findall("require"):
            defined.update(child.get("name") for child in requirement.findall("command"))
        for name in wanted:
            if name not in defined:
                sys.exit("gl.xml: %s does not define %s" % (extension, name))
            names.append(name)
    if names != gen_stubs.gles_ext_names():
        sys.exit("gen_stubs.gles_ext_names() disagrees with GLES_EXTENSIONS")
    if len(names) != EXPECTED_EXT:
        sys.exit("expected %d extension entry points, got %d" % (EXPECTED_EXT, len(names)))
    return names


def registry_commands():
    root = ET.parse(REGISTRY).getroot()
    # GL_ES_VERSION_3_0 lists only what 2.0 does not already require.
    names = (feature_names(root, "GL_ES_VERSION_2_0", EXPECTED_GLES) +
             feature_names(root, "GL_ES_VERSION_3_0", EXPECTED_GLES3) +
             extension_names(root))

    definitions = {}
    for node in root.findall("./commands/command"):
        proto = node.find("proto")
        if proto is None:
            continue
        name = proto.findtext("name")
        definitions[name] = node

    commands = {}
    for name in names:
        node = definitions.get(name)
        if node is None:
            sys.exit("gl.xml: command definition missing for " + name)
        proto = element_text(node.find("proto"))
        if not proto.endswith(name):
            sys.exit("gl.xml: malformed prototype for " + name)
        result = proto[:-len(name)].strip()
        parameters = []
        for param in node.findall("param"):
            param_name = param.findtext("name")
            declaration = element_text(param)
            if not param_name or not re.search(r"\b%s\b" % re.escape(param_name), declaration):
                sys.exit("gl.xml: malformed parameter in " + name)
            parameters.append(Parameter(declaration, param_name, param.get("len")))
        commands[name] = Command(name, result, parameters)
    return commands


def committed_hostcalls():
    rows = []
    row = re.compile(r'^\{(\d+), "([^"]+)", "([^"]+)"\},$')
    with open(HOSTCALLS) as source:
        for line in source:
            match = row.match(line.strip())
            if match:
                rows.append((int(match.group(1)), match.group(2), match.group(3)))
    return rows


def checked_surface():
    commands = registry_commands()
    header_names = gen_stubs.gles2_names()
    header3_names = gen_stubs.gles3_names()
    registry_names = sorted(commands)
    if len(header_names) != EXPECTED_GLES:
        sys.exit("gl2.h: expected %d functions, got %d" % (EXPECTED_GLES, len(header_names)))
    if len(header3_names) != EXPECTED_GLES3:
        sys.exit("gl3.h: expected %d new functions, got %d" % (EXPECTED_GLES3, len(header3_names)))
    # The extension entry points have no NDK header to cross-check against: gl.xml is their only
    # source, and extension_names() already checked each one against its <extension> block.
    exported = set(header_names) | set(header3_names) | set(gen_stubs.gles_ext_names())
    missing_header = sorted(set(registry_names) - exported)
    missing_registry = sorted(exported - set(registry_names))
    if missing_header or missing_registry:
        sys.exit("GLES surface mismatch: registry-only=%s header-only=%s" %
                 (missing_header, missing_registry))

    # Built from every stub library gen_stubs.py knows, so adding a library (libEGL, the
    # ANativeWindow_* names) does not break this check. What matters here is that the GLES rows
    # still start at 0 and keep their order.
    expected_rows = []
    index = 0
    for lib, source in gen_stubs.LIBRARIES:
        for name in source():
            expected_rows.append((index, lib + ".so", name))
            index += 1
    actual_rows = committed_hostcalls()
    if actual_rows != expected_rows:
        sys.exit("core/src/gen/hostcalls.inc disagrees with tools/gen_stubs.py")

    # GLES 2.0 owns host-call indices 0-141 and GLES 3.0 a second block appended at the end of
    # the stub table, so every command carries the index gen_stubs.py assigned it.
    index_of = {name: index for index, lib, name in expected_rows if lib == "libGLESv2.so"}
    ext_names = gen_stubs.gles_ext_names()
    ordered = [(index_of[name], commands[name]) for name in header_names]
    ordered3 = [(index_of[name], commands[name]) for name in header3_names]
    orderedext = [(index_of[name], commands[name]) for name in ext_names]
    for block, first, count in ((ordered, 0, EXPECTED_GLES),
                                (ordered3, ordered3[0][0], EXPECTED_GLES3),
                                (orderedext, orderedext[0][0], EXPECTED_EXT)):
        if [index for index, _ in block] != list(range(first, first + count)):
            sys.exit("gen_stubs.py no longer assigns the GLES commands a contiguous index block")
    for expected, actual, label in ((EXPECTED_POINTERLESS,
                                     sum(not command.pointer for _, command in ordered), "GLES 2.0"),
                                    (EXPECTED_GLES3_POINTERLESS,
                                     sum(not command.pointer for _, command in ordered3), "GLES 3.0"),
                                    (EXPECTED_TASK3_MECHANICAL,
                                     sum(mechanical(command) for _, command in ordered), "GLES 2.0"),
                                    (EXPECTED_GLES3_MECHANICAL,
                                     sum(mechanical(command) for _, command in ordered3), "GLES 3.0"),
                                    (EXPECTED_EXT_POINTERLESS,
                                     sum(not command.pointer for _, command in orderedext), "extension"),
                                    (EXPECTED_EXT_MECHANICAL,
                                     sum(mechanical(command) for _, command in orderedext), "extension")):
        if expected != actual:
            sys.exit("gl.xml: expected %d %s commands in that class, got %d" %
                     (expected, label, actual))
    return ordered + ordered3 + orderedext


def backend_header(commands):
    lines = [
        "// " + HEADER,
        "#pragma once",
        "",
        "#include <bit>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <initializer_list>",
        "#include <type_traits>",
        "",
        "namespace zb {",
        "",
        "using GLbitfield = std::uint32_t;",
        "using GLboolean = std::uint8_t;",
        "using GLchar = char;",
        "using GLenum = std::uint32_t;",
        "using GLfloat = float;",
        "using GLint = std::int32_t;",
        "using GLint64 = std::int64_t;",
        "using GLintptr = std::intptr_t;",
        "using GLsizei = std::int32_t;",
        "using GLsizeiptr = std::ptrdiff_t;",
        "using GLubyte = std::uint8_t;",
        "using GLuint = std::uint32_t;",
        "using GLuint64 = std::uint64_t;",
        "// GLES 3.0 sync objects are driver pointers. They never reach the guest: HostGl hands",
        "// out 32-bit handles and keeps the GLsync values host-side.",
        "using GLsync = void*;",
        "",
        "inline constexpr GLenum kGlInvalidValue = 0x0501;",
        "inline constexpr GLenum kGlInvalidOperation = 0x0502;",
        "inline constexpr GLenum kGlOutOfMemory = 0x0505;",
        "",
        "template <typename T>",
        "inline std::uint64_t gl_backend_word(T value) {",
        "    if constexpr (std::is_pointer_v<T>) {",
        "        return static_cast<std::uint64_t>(reinterpret_cast<std::uintptr_t>(value));",
        "    } else if constexpr (std::is_floating_point_v<T>) {",
        "        return std::bit_cast<std::uint32_t>(value);",
        "    } else {",
        "        return static_cast<std::uint64_t>(value);",
        "    }",
        "}",
        "",
        "// The portable GLES seam. Android overrides the typed entry points; host tests use",
        "// invoke() to record the same typed calls without linking a GLES implementation.",
        "class GlBackend {",
        "public:",
        "    virtual ~GlBackend() = default;",
        "    virtual void set_error(GLenum error) = 0;",
        "",
    ]
    for _, command in commands:
        params = ", ".join(parameter.declaration for parameter in command.parameters) or "void"
        args = ", ".join("gl_backend_word(%s)" % parameter.name for parameter in command.parameters)
        invocation = 'invoke("%s", {%s})' % (command.name, args)
        lines.append("    virtual %s %s(%s) {" % (command.result, command.name, params))
        if command.result == "void":
            lines.append("        (void)%s;" % invocation)
        elif "*" in command.result or command.result == "GLsync":
            lines.append("        return reinterpret_cast<%s>(static_cast<std::uintptr_t>(%s));" %
                         (command.result, invocation))
        else:
            lines.append("        return static_cast<%s>(%s);" % (command.result, invocation))
        lines.append("    }")
    lines += [
        "",
        "protected:",
        "    virtual std::uint64_t invoke(const char* name,",
        "                                 std::initializer_list<std::uint64_t> arguments) = 0;",
        "};",
        "",
        "}  // namespace zb",
    ]
    return "\n".join(lines) + "\n"


def hostcalls_header(commands):
    gles3_first = commands[EXPECTED_GLES][0]
    ext_first = commands[EXPECTED_GLES + EXPECTED_GLES3][0]
    pointerless = sum(not command.pointer for _, command in commands)
    lines = [
        "// " + HEADER,
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace zb {",
        "",
        "// Three blocks: GLES 2.0 at 0-%d, then GLES 3.0 and the curated extension entry" % (EXPECTED_GLES - 1),
        "// points, both appended after every other stub library so no established host-call",
        "// index moved.",
        "inline constexpr std::uint32_t kGlHostCallFirst = 0;",
        "inline constexpr std::uint32_t kGlHostCallLast = %du;" % (EXPECTED_GLES - 1),
        "inline constexpr std::size_t kGlHostCallCount = %du;" % EXPECTED_GLES,
        "inline constexpr std::uint32_t kGlHostCall3First = %du;" % gles3_first,
        "inline constexpr std::uint32_t kGlHostCall3Last = %du;" % (gles3_first + EXPECTED_GLES3 - 1),
        "inline constexpr std::size_t kGlHostCall3Count = %du;" % EXPECTED_GLES3,
        "inline constexpr std::uint32_t kGlHostCallExtFirst = %du;" % ext_first,
        "inline constexpr std::uint32_t kGlHostCallExtLast = %du;" % (ext_first + EXPECTED_EXT - 1),
        "inline constexpr std::size_t kGlHostCallExtCount = %du;" % EXPECTED_EXT,
        "inline constexpr std::size_t kGlHostCallTotalCount = %du;" % len(commands),
        "inline constexpr std::size_t kGlPointerlessHostCallCount = %du;" % pointerless,
        "",
    ]
    for index, command in commands:
        lines.append("inline constexpr std::uint32_t ZB_GL_HC_%s = %du;" %
                     (command.name, index))
    lines += [
        "",
        "struct GlHostCallInfo {",
        "    std::uint32_t index;",
        "    const char* name;",
        "    bool has_pointer;",
        "};",
        "",
        "// GLES 2.0 first, then GLES 3.0, then the extensions; use gl_host_call() rather than",
        "// indexing by host call.",
        "inline constexpr std::array<GlHostCallInfo, kGlHostCallTotalCount> kGlHostCalls{{",
    ]
    for index, command in commands:
        lines.append('    {%du, "%s", %s},' %
                     (index, command.name, "true" if command.pointer else "false"))
    lines += [
        "}};",
        "",
        "inline constexpr const GlHostCallInfo* gl_host_call(std::uint32_t index) {",
        "    if (index <= kGlHostCallLast) return &kGlHostCalls[index];",
        "    if (index >= kGlHostCall3First && index <= kGlHostCall3Last) {",
        "        return &kGlHostCalls[kGlHostCallCount + (index - kGlHostCall3First)];",
        "    }",
        "    if (index >= kGlHostCallExtFirst && index <= kGlHostCallExtLast) {",
        "        return &kGlHostCalls[kGlHostCallCount + kGlHostCall3Count +",
        "                             (index - kGlHostCallExtFirst)];",
        "    }",
        "    return nullptr;",
        "}",
        "",
        "inline constexpr bool is_gl_host_call(std::uint32_t index) {",
        "    return gl_host_call(index) != nullptr;",
        "}",
        "",
        "inline constexpr const char* gl_host_call_name(std::uint32_t index) {",
        "    const GlHostCallInfo* info = gl_host_call(index);",
        "    return info == nullptr ? \"?\" : info->name;",
        "}",
        "",
        "}  // namespace zb",
    ]
    return "\n".join(lines) + "\n"


def parameter_type(parameter):
    return parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()


def extension_entries(commands):
    """The X-macro list behind GlDriverBackend's lazily resolved extension entry points.

    ZB_GL_EXT_ENTRY(slot, name, result, declaration, types, arguments): `slot` indexes the
    driver's per-entry cache, `types` builds the function-pointer type eglGetProcAddress's
    result is cast to, and `declaration`/`arguments` are the GlBackend override.
    """
    lines = [
        "// " + HEADER,
        "// Extension entry points from tools/gen_stubs.py's GLES_EXTENSIONS. They are not",
        "// linkable NDK symbols, so the Android backend resolves each one through the real",
        "// eglGetProcAddress on first use (core/android/gl_driver_backend.cpp).",
        "// ZB_GL_EXT_ENTRY(slot, name, result, declaration, types, arguments)",
    ]
    extension = [command for _, command in commands[EXPECTED_GLES + EXPECTED_GLES3:]]
    for slot, command in enumerate(extension):
        declaration = ", ".join(p.declaration for p in command.parameters) or "void"
        types = ", ".join(parameter_type(p) for p in command.parameters) or "void"
        arguments = ", ".join(p.name for p in command.parameters)
        lines.append("ZB_GL_EXT_ENTRY(%d, %s, %s, (%s), (%s), (%s))" %
                     (slot, command.name, command.result, declaration, types, arguments))
    return "\n".join(lines) + "\n"


def manual_include(commands):
    lines = [
        "// " + HEADER,
    ]
    for _, command in commands:
        if not mechanical(command):
            lines.append("bool zbgl_manual_%s(HostGl& host, HostGl::Call& call);" % command.name)
    return "\n".join(lines) + "\n"


def dispatch_include(commands):
    lines = [
        "// " + HEADER,
        "bool HostGl::dispatch(Call& call) {",
        "    switch (call.index()) {",
    ]
    for _, command in commands:
        lines.append("    case ZB_GL_HC_%s: {" % command.name)
        if not mechanical(command):
            lines.append("        return zbgl_manual_%s(*this, call);" % command.name)
        else:
            for position, parameter in enumerate(command.parameters):
                if parameter.pointer:
                    continue
                ptype = parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()
                lines.append("        const %s %s = call.scalar<%s>(%d);" %
                             (ptype, parameter.name, ptype, position))
            for position, parameter in enumerate(command.parameters):
                if not parameter.pointer:
                    continue
                declaration = parameter.declaration[:parameter.declaration.rfind(parameter.name)].strip()
                pointee = pointer_pointee(parameter)
                length_name, multiplier = length_rule(command, parameter)
                if length_name is None:
                    elements = "%du" % multiplier
                else:
                    elements = "call.length(%s, %du)" % (length_name, multiplier)
                permission = "kPageRead" if "const" in pointee.split() else "kPageRead | kPageWrite"
                lines.append("        %s %s = call.pointer<%s>(%d, %s, %s);" %
                             (declaration, parameter.name, pointee, position, elements, permission))
            lines.append("        if (!call.valid()) return true;")
            args = ", ".join(parameter.name for parameter in command.parameters)
            invocation = "backend_.%s(%s)" % (command.name, args)
            if command.result == "void":
                lines.append("        %s;" % invocation)
                if command.name == "glPixelStorei":
                    lines.append("        note_pixel_store(pname, param);")
                elif command.name in ("glLinkProgram", "glDeleteProgram"):
                    lines.append("        invalidate_uniforms(program);")
                elif command.name == "glBindBuffer":
                    lines.append("        note_bind_buffer(target, buffer);")
                elif command.name == "glEnableVertexAttribArray":
                    lines.append("        note_vertex_attrib_enabled(index, true);")
                elif command.name == "glDisableVertexAttribArray":
                    lines.append("        note_vertex_attrib_enabled(index, false);")
            else:
                lines.append("        call.set_result(%s);" % invocation)
            lines.append("        return true;")
        lines.append("    }")
    lines += [
        "    default:",
        "        return false;",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def generate():
    commands = checked_surface()
    return {
        "core/include/zb/gl_backend.h": backend_header(commands),
        "core/include/zb/gl_hostcalls.h": hostcalls_header(commands),
        "core/src/gen/gl_dispatch.inc": dispatch_include(commands),
        "core/src/gen/gl_manual.inc": manual_include(commands),
        "core/include/zb/gl_ext_entries.inc": extension_entries(commands),
    }


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        sys.exit("usage: gen_gles.py [--check]")
    stale = []
    for path, content in generate().items():
        full = os.path.join(ROOT, path)
        if check:
            try:
                with open(full) as source:
                    current = source.read()
            except OSError:
                current = None
            if current != content:
                stale.append(path)
        else:
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w") as output:
                output.write(content)
            print("wrote " + path)
    if stale:
        print("stale generated files (run tools/gen_gles.py): " + ", ".join(stale))
        sys.exit(1)
    if check:
        print("generated GLES files are up to date")


if __name__ == "__main__":
    main()
